CAMDEN sync names with repo
ESCOMP/CCPPStandardNames pull request #10
Opened 2021-04-01 20:25 UTC by cacraigucar

Synchronize standard_names used in CAMDEN with input from list from WRF and NOAA SCM model.  Also get input from the CF conventions and attempt to adhere to NOAA's CCPP naming guidelines.

closes #8

2021-04-01 21:35 UTC, peverwhee commented on standard_names.xml
> +    <standard_name name="boltzman_constant">
Should this be "boltzmann_constant" ?

2021-04-01 21:35 UTC, peverwhee commented on standard_names.xml
> +      <type kind="kind_phys" units="??????????">real</type>
I would imagine that the units would be the same as the specific_heat_of_dry_air_at_constant_pressure. 
`J kg-1 K-1`

2021-04-01 21:43 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="boltzman_constant">
Good catch!

2021-04-01 21:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="??????????">real</type>
That is my guess as well, but I wasn't sure if the "at constant pressure" changed the units.  Since I wasn't 100% sure, I wanted to get confirmation.

2021-04-02 18:12 UTC, peverwhee approved these changes

2021-04-06 03:30 UTC, nusbaume requested changes
Looks pretty good, but I do have some concerns/requests, which are mostly related to units.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
> +      <type kind="kind_phys" units="radian+2">real</type>
Should the units here be `radian2` or `radian+2`?  Basically I am asking what the standard representation of a positive exponent should be.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
>        <type kind="kind_phys" units="Pa s2 m-1">real</type>
These units seem like an overly-complicated way of saying `kg m-2`.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
>        <type kind="kind_phys" units="Pa s2 m-1">real</type>
These units seem like an overly-complicated way of saying `kg m-2`.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
> +      <type kind="kind_phys" units="mb">real</type>
I believe the units here should be `Pa`.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
> +      <type kind="kind_phys" units="mb">real</type>
I believe the units here should be `Pa`.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
> +      <type kind="kind_phys" units="mb">real</type>
I believe the units here should be `Pa`.

2021-04-06 03:30 UTC, nusbaume commented on standard_names.xml
>        <type kind="kind_phys" units="mb">real</type>
I believe this quantity is unitless.

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="radian+2">real</type>
@gold2718 Is there a "rule" for this?

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="molecules kmole-1">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="molecules kmole-1">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="??????????">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="kg m-3"></type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="none">integer</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>                     long_name="Zonal wind">
@gold2718 Do you agree that there should be a long_name for the wind?

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="J m-2">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="pmid">real</type>
Used ln(Pa) as that is what is used elsewhere in this document

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="Pa s2 m-1">real</type>
@gold2718  I changed to Jesse's suggestion.  Are you okay with this?

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="Pa s2 m-1">real</type>
@gold2718 Same question here

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="mb">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="mb">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="mb">real</type>
fixed

2021-04-06 19:44 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="mb">real</type>
fixed

2021-04-06 20:15 UTC, gold2718 commented on standard_names.xml
>                     long_name="Zonal wind">
@davegill, do you folks have a plan here? What do you usually call `X_wind` (besides x wind)?

2021-04-06 20:56 UTC, gold2718 commented on standard_names.xml
> +      <type kind="kind_phys" units="radian+2">real</type>
Isn't this a `steradian`?

2021-04-06 20:59 UTC, gold2718 commented on standard_names.xml
>        <type kind="kind_phys" units="Pa s2 m-1">real</type>
Yes, it makes sense and seems to align with similar quantities in CF.

2021-04-06 20:59 UTC, gold2718 commented on standard_names.xml
>        <type kind="kind_phys" units="Pa s2 m-1">real</type>
Same answser

2021-04-07 17:41 UTC, cacraigucar commented on standard_names.xml
> +      <type kind="kind_phys" units="radian+2">real</type>
The standard is radian2 (no +).  But this unit should actually be `streadian`.

2021-04-07 17:46 UTC, cacraigucar commented on standard_names.xml
>        <type kind="kind_phys" units="pmid">real</type>
After consultation with @gold2718, all units ln(Pa) will be changed to `1`

2021-04-08 00:09 UTC, gold2718 requested changes
A few nits and questions.
Also, we need back long names for `x_wind` and `y_wind`.

2021-04-08 15:53 UTC, cacraigucar commented on standard_names.xml
>      </standard_name>
Because I missed the comment above.  Comment is corrected to match the NOAA guidelines "on_previous_timestep"

2021-04-08 15:53 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="flag_for_physics_grid_initialization">
check the long name I created and make suggestion if needed

2021-04-08 15:53 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="column_integrated_total_water_of_new_state">
Because that is what the initial contributor wrote and I didn't see the error :-)  Fixed

2021-04-08 18:41 UTC, nusbaume approved these changes
Everything looks good now (assuming we hear back about the wind component long names).  Thanks for tackling this!

2021-04-08 19:19 UTC, nusbaume commented
@cacraigucar That sounds like a reasonable plan to me!  I just didn't want to to make it seem as if I had completely skipped over long names in my re-review.

2021-04-13 18:28 UTC, gold2718 requested changes
A few items, notably long names for wind fields.

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
> +    <standard_name name="equivalent_potential_temperature">
Is this ever used in CAM? I have no idea what this means, perhaps we should not have it.

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
>                     long_name="Zonal wind">
How about this for a long name?
```suggestion
                   long_name="Horizontal wind in a direction perpendicular to y_wind">
```

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
>                     long_name="Meridional wind">
```suggestion
                   long_name="Horizontal wind in a direction perpendicular to x_wind">
```

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
>      <standard_name name="exner_function"
Units should be `1`.

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
> +    <standard_name name="inverse_dimensionless_exner_function_wrt_surface_pressure"
Where did `_dimensionless` come from? Isn't the exner function (and therefore its inverse) always dimensionless?

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
>                     long_name="Change in zonal wind from a parameterization">
```suggestion
                   long_name="Change in x wind from a parameterization">
```

2021-04-13 18:28 UTC, gold2718 commented on standard_names.xml
>                     long_name="Change in meridional from a parameterization">
```suggestion
                   long_name="Change in y from a parameterization">
```

2021-04-13 18:58 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="equivalent_potential_temperature">
Agree - it does not appear to be used.  Will remove it.

2021-04-13 19:01 UTC, cacraigucar commented on standard_names.xml
>                     long_name="Meridional wind">
Tentatively applying these long names unless @nusbaume or @peverwhee have a better suggestion.

2021-04-13 19:02 UTC, cacraigucar commented on standard_names.xml
>      <standard_name name="exner_function"
???   Units do appear to be 1?

2021-04-13 19:02 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="inverse_dimensionless_exner_function_wrt_surface_pressure"
@nusbaume - You wanted dimensionless.  Can you please explain your rationale?

2021-04-13 19:04 UTC, cacraigucar commented on standard_names.xml
>                     long_name="Change in meridional from a parameterization">
I would suggest it being "Change in y wind from a parameterization"  The word "wind" was missing from the description

2021-04-13 19:25 UTC, nusbaume commented on standard_names.xml
> +    <standard_name name="equivalent_potential_temperature">
It's fine to remove this if we aren't using it, but I should note that equivalent potential temperature is a standard meteorological variable:

https://glossary.ametsoc.org/wiki/Equivalent_potential_temperature

So there is a good chance we will need to add it back in someday.

2021-04-13 19:28 UTC, nusbaume commented on standard_names.xml
>                     long_name="Meridional wind">
Should we add something like `grid-dependent` or `dycore-dependent` to the long name?  Otherwise this name is fine with me, at least until we get more scientists to way in.

2021-04-13 19:33 UTC, nusbaume commented on standard_names.xml
> +    <standard_name name="inverse_dimensionless_exner_function_wrt_surface_pressure"
I think maybe I just added it to be (overly) precise?  I agree with @gold2718 that the exner function is always dimensionless (to my knowledge), so we can probably drop `dimensionless` from the name.

2021-04-13 20:32 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="inverse_dimensionless_exner_function_wrt_surface_pressure"
Removed

2021-04-15 22:28 UTC, gold2718 commented on standard_names.xml
>      <standard_name name="exner_function"
Units on `exner_function` still seem to be `none`.

2021-04-15 22:31 UTC, gold2718 requested changes
A few open issues but (at least) one bad unit still.

2021-04-15 22:31 UTC, gold2718 commented on standard_names.xml
>      <standard_name name="exner_function"
Units on `exner_function` still seem to be `none`

2021-04-15 22:38 UTC, cacraigucar commented on standard_names.xml
>      <standard_name name="exner_function"
The highlighted code was reference_pressure...   

Fixed units for exner function

2021-04-15 22:39 UTC, cacraigucar commented
When I went through before, I believe the only open issues are ones that I'm unable to do anything about.  If there is anything that should be dealt with, please let me know.

2021-04-15 23:03 UTC, gold2718 commented
> When I went through before, I believe the only open issues are ones that I'm unable to do anything about. If there is anything that should be dealt with, please let me know.

Agreed, we will need to deal with these later

2021-04-15 23:04 UTC, gold2718 approved these changes
Ok for now

2021-04-16 14:50 UTC, merged