modified:   Metadata-standard-names.md
ESCOMP/CCPPStandardNames pull request #13
Opened 2021-05-07 00:08 UTC by bluefinweiwei

The following two files were changed with the CCPP standard names that are contained under [non-category] section.
	modified:   standard_names.xml
	modified:   Metadata-standard-names.md

2021-05-13 17:29 UTC, cacraigucar reviewed
FIrst set of comments/questions

2021-05-13 17:29 UTC, cacraigucar commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = degree_north
I agree that degree_north is the CF standard for latitude.  @gold2718 do we need to temporarily bring in a latitude_radians until CCPP has unit conversion?

2021-05-13 17:29 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
Agree this is the CF name

2021-05-18 22:16 UTC, grantfirl commented on Metadata-standard-names.md
> +* `vertical_dimension_plus_one`: number of vertical levels + 1
You're right. You must have a better memory than me, but I did find what we agreed upon here: https://github.com/NCAR/ccpp-framework/wiki/CCPP-Framework-Meeting-Minutes-2019-08-15

2021-05-18 22:21 UTC, grantfirl commented on Metadata-standard-names.md
> +* `vertical_index_at_surface_adjacent_layer`: Vertical index at surface adjacent layer
I think that we included "vertical_index_at..." due to the need to reference multiple-dimensioned arrays. If we only have "index_of" it could be too imprecise? I suppose that whatever you have after the "at" would give you a clue as to the spatial dimension or whatever, though, so maybe it could be sufficient. Other opinions?

2021-05-18 22:52 UTC, grantfirl commented on Metadata-standard-names.md
> +* `surface_dry_air_pressure`: Surface dry air pressure
"surface" is a prefix according to CF, which CCPP standard names should inherit. If you search CF names for "pressure", you'll see inconsistencies about whether they put what the pressure refers to either before or after, so we should probably just identify the most general approach and stick with it. I think pressure_of_X is fine, and we can revert this.

2021-05-18 22:56 UTC, grantfirl commented on Metadata-standard-names.md
> +* `tendency_of_air_temperature_due_to_X`: Change in temperature from a parameterization
For the UFS-based use-case, the tendencies are almost all diagnostic, so due_to_X was necessary to differentiate. CF does have a straight "tendency_of_air_temperature" that could be used, so maybe this existing entry should be changed to just that? And we could add the "tendency_of_air_temperature_due_to_X" as another, distinct (family of) name(s).

2021-05-18 22:57 UTC, grantfirl commented on Metadata-standard-names.md
> +* `tendency_of_air_temperature_due_to_X`: Change in temperature from a parameterization
CF has a million names with "due_to_X", so that horse is already out of the barn in terms of standard names in general.

2021-05-20 22:46 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `vertical_index_at_surface_adjacent_layer`: Vertical index at surface adjacent layer
I think that using _vertical_ is more precise because there are other cases in which we refer to indices in other dimensions.

2021-05-20 22:50 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `tendency_of_air_temperature_due_to_model_physics`: Total change in temperature from a                               physics suite
Wouldn't `total_tendency_of_air_temperature` sound like it includes dynamics (since it has the word `total` in it)? It seems that `tendency_of_air_temperature_due_to_model_physics` is more precise.

2021-05-20 22:56 UTC, ligiabernardet commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = degree_north
I believe @gold2718 asked us to stay away from putting units on the standard names because it makes it harder to use automatic unit conversions. But we may need some exceptions until the auto conversions are adopted

2021-05-21 17:39 UTC, dudhia commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = degree_north
maybe standard temperature and freezing point could be used to avoid units

2021-05-21 17:39 UTC, dudhia commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
Is this 3d as in layer or just surface? Check.

2021-05-21 17:39 UTC, dudhia commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
Is it layer by default for 3d?

2021-05-21 17:39 UTC, dudhia commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
I assume layer variables will be clear by their vertical dimension attribute

2021-05-21 17:39 UTC, dudhia commented on Metadata-standard-names.md
> +## non-category
are we supposed to review these? - many repetitions and variables with names specific to rrtmgp for example

2021-05-21 17:50 UTC, dudhia commented
Not able to open standard_names.xml. Do we need to review this file too?

2021-05-21 19:29 UTC, ligiabernardet commented
@dudhia It is sufficient to review the .md file since it is created from the .xml file.

2021-05-21 19:35 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
I agree it should be reference_pressure (per CF). This is not 3D or just a surface, it is simply a scalar: A constant pressure value, typically representative of mean sea level pressure, which can be used in defining coordinates or functions of state.

2021-05-21 19:38 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
@dudhia, The rules we proposed (https://github.com/ESCOMP/CCPPStandardNames/pull/14/) indicate that: _By default (when not specified otherwise), variables are grid means or centers (defined by the host). If a variable is defined at a different physical location,  a qualifier should be used to denote this. For example, for variables representing quantities at the interface between grid cells vertically, use at_interface._

2021-05-21 19:42 UTC, ligiabernardet commented on Metadata-standard-names.md
> +## non-category
@dudhia Yes, please review the non-categorized names since they are an integral part of the dictionary of standard names.

2021-05-21 19:50 UTC, dudhia commented
I saw many duplications in there so I wondered if it was generated
correctly.

On Fri, May 21, 2021 at 1:42 PM ligiabernardet ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Metadata-standard-names.md
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r637183364>
> :
>
> >      * `real(kind=kind_phys)`: units = kg kg-1
>  ## standard_variables
>  Standard / required CCPP variables
>  * `ccpp_error_message`: Error message for error handling in CCPP
>      * `character(kind=len=512)`: units = 1
>  * `ccpp_error_flag`: Error flag for error handling in CCPP
>      * `integer(kind=)`: units = flag
> +## non-category
>
> @dudhia <https://github.com/dudhia> Yes, please review the
> non-categorized names since they are an integral part of the dictionary of
> standard names.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r637183364>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77FAZOSQ2OC5SFLEWG3TO2ZRPANCNFSM44IFYSVA>
> .
>

2021-05-21 20:05 UTC, dudhia commented
I believe there are four full repeats of over 2000 lines after about 6000
lines

On Fri, May 21, 2021 at 1:50 PM Jimy Dudhia ***@***.***> wrote:

> I saw many duplications in there so I wondered if it was generated
> correctly.
>
> On Fri, May 21, 2021 at 1:42 PM ligiabernardet ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In Metadata-standard-names.md
>> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r637183364>
>> :
>>
>> >      * `real(kind=kind_phys)`: units = kg kg-1
>>  ## standard_variables
>>  Standard / required CCPP variables
>>  * `ccpp_error_message`: Error message for error handling in CCPP
>>      * `character(kind=len=512)`: units = 1
>>  * `ccpp_error_flag`: Error flag for error handling in CCPP
>>      * `integer(kind=)`: units = flag
>> +## non-category
>>
>> @dudhia <https://github.com/dudhia> Yes, please review the
>> non-categorized names since they are an integral part of the dictionary of
>> standard names.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r637183364>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AEIZ77FAZOSQ2OC5SFLEWG3TO2ZRPANCNFSM44IFYSVA>
>> .
>>
>

2021-05-21 20:05 UTC, dudhia commented on Metadata-standard-names.md
> +* `height_of_launch_level_of_orographic_gravity_wave`: Height of launch level of orographic grav
spelling

2021-05-21 20:10 UTC, dudhia commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
OK, maybe reference_sea_level_pressure then to imply it is a level

2021-05-21 20:20 UTC, dudhia commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
reference_pressure_at_sea_level according to naming rules

2021-05-21 20:37 UTC, grantfirl commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
I think that we need more information about what this variable is from @cacraigucar . In my opinion, even though "reference_pressure" is in the CF standards, it is hopelessly vague. Reference for what? Pressure of what? Is it a profile of reference air pressures? From what @ligiabernardet and @dudhia are describing, that name provided by CF is reference_air_pressure_for_atmosphere_vertical_coordinate, which is also already below.

2021-05-21 20:46 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
@gold2718 - Could you please weigh in on this one?

2021-05-24 16:26 UTC, dudhia commented on Metadata-standard-names.md
> +* `RRTMGP_lw_fluxes`: RRTMGP lw fluxes
standards names should avoid parameterization names (many with RRTMGP here)

2021-05-24 16:33 UTC, dudhia commented on Metadata-standard-names.md
> +* `RRTMGP_sw_fluxes`: RRTMGP sw fluxes
Standard names for arrays should avoid parameterization names where possible - many with RRTMGP

2021-05-24 16:39 UTC, dudhia commented on Metadata-standard-names.md
> +* `flag_for_shoc`: Flag for shoc
repeat section starts here

2021-05-24 16:40 UTC, dudhia commented on Metadata-standard-names.md
> +* `flag_for_shoc`: Flag for shoc
3rd repeat section starts here

2021-05-24 16:41 UTC, dudhia commented on Metadata-standard-names.md
> +* `identifier_for_2018_scale_aware_tke_moist_edmf_pbl`: Identifier for 2018 scale aware tke moist edmf pbl
3rd repeat section ends here

2021-05-24 16:44 UTC, grantfirl commented on Metadata-standard-names.md
> +* `RRTMGP_sw_fluxes`: RRTMGP sw fluxes
Yes. This variable corresponds to the portion of UFS standard names that have not been gone through yet. There are probably 1/3 of the names in this PR that have not been "fixed" to be consistent with our own rules. Having said that, some variables will need to retain names that may make them non-portable. This one, for example, is referring to a DDT defined by RRTMGP, so it's hard to imagine not referring to RRTMGP in this case.

2021-05-24 16:45 UTC, dudhia commented on Metadata-standard-names.md
> +* `height_of_launch_level_of_orographic_gravity_wave`: Height of launch level of orographic grav
longer repeat section starts here

2021-05-24 16:45 UTC, dudhia commented on Metadata-standard-names.md
> +* `height_of_launch_level_of_orographic_gravity_wave`: Height of launch level of orographic grav
2nd longer repeat section starts here

2021-05-24 16:46 UTC, dudhia commented on Metadata-standard-names.md
> +* `height_of_launch_level_of_orographic_gravity_wave`: Height of launch level of orographic grav
3rd longer repeat section starts here

2021-05-24 16:47 UTC, dudhia commented on Metadata-standard-names.md
> +* `height_of_launch_level_of_orographic_gravity_wave`: Height of launch level of orographic grav
4th longer repeat section starts here

2021-05-24 16:49 UTC, grantfirl commented on Metadata-standard-names.md
> +* `height_of_launch_level_of_orographic_gravity_wave`: Height of launch level of orographic grav
Thanks. Should definitely be fixed. This one comes from a DDT that Ligia and I already processed, but the name snuck in a recent commit, well after we had already processed the group of names where this now is.

2021-05-24 16:53 UTC, grantfirl commented on Metadata-standard-names.md
> +* `flag_for_shoc`: Flag for shoc
@bluefinweiwei Is this repetition coming from the script? As far as I know, there isn't replication like this in the spreadsheet that we were working with. If this is coming from the script, could you look into it please?

2021-05-24 17:02 UTC, dudhia commented on Metadata-standard-names.md
> +* `flag_for_shoc`: Flag for shoc
2nd repeat section starts here

2021-05-24 20:11 UTC, grantfirl commented
@dudhia and @cacraigucar We're pushing a commit sans-duplication in a bit. Thanks for IDing the 4X duplication @dudhia. This should make it (slightly) easier to review.

2021-05-24 20:47 UTC, grantfirl commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = degree_north
degree_north and degree_east are the "canonical" units in CF for lat/lon. I agree that radians makes more sense for scientific programming, but either we stick with existing standards or we don't. We have a tab on our spreadsheet to try to capture disagreements with CF standards, so we could put this in there.

We actually have variables/std names for latitude/longitude_in_radians below, although they should be superfluous with unit conversion. This one might be a bit trickier than most because the conversion may need to put bounds on the data, right? (latitude degree between -90-90, radian between -pi/2,pi/2 ...)

@dudhia, I'm not understanding standard temperature/freezing point's relation to lat/lon here. Was this comment supposed to refer to other variables?

2021-05-24 21:22 UTC, dudhia commented
It was to avoid references to things that needed units like 0 deg C or 20
deg C in response to earlier comments on the thread.

On Mon, May 24, 2021 at 2:47 PM grantfirl ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Metadata-standard-names.md
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r638260953>
> :
>
> >  * `latitude`: Latitude
> -    * `real(kind=kind_phys)`: units = radians
> +    * `real(kind=kind_phys)`: units = degree_north
>
> degree_north and degree_east are the "canonical" units in CF for lat/lon.
> I agree that radians makes more sense for scientific programming, but
> either we stick with existing standards or we don't. We have a tab on our
> spreadsheet to try to capture disagreements with CF standards, so we could
> put this in there.
>
> We actually have variables/std names for latitude/longitude_in_radians
> below, although they should be superfluous with unit conversion. This one
> might be a bit trickier than most because the conversion may need to put
> bounds on the data, right? (latitude degree between -90-90, radian between
> -pi/2,pi/2 ...)
>
> @dudhia <https://github.com/dudhia>, I'm not understanding standard
> temperature/freezing point's relation to lat/lon here. Was this comment
> supposed to refer to other variables?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r638260953>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77BBEURANFB6BXWJDTDTPK3PBANCNFSM44IFYSVA>
> .
>

2021-05-24 23:37 UTC, grantfirl commented
Once @bluefinweiwei accepts/merges a PR into her branch, there is a bit more duplication removal and modifications to the XML/md to address several comments. I also added a simple script to report on duplicates (but not remove -- still need to finish that code).

Note that the XML file in this PR does not pass the XML validation due to a bunch of capital letters (if not other things as well). We can fix that if necessary.

2021-05-25 18:07 UTC, dudhia commented on Metadata-standard-names.md
>  * `vertical_layer_index`: index of a particular vertical level
some consistency is needed to remove the word level from the comments and just use layer everywhere as distinct from interfaces

2021-05-25 18:13 UTC, dudhia commented on Metadata-standard-names.md
> +* `flag_for_generic_tendency_due_to_plantary_boundary_layer`: Flag for generic tendency due to plantary boundary layer
sp. planetary

2021-05-25 21:09 UTC, dudhia commented on Metadata-standard-names.md
> +* `cloud_overlap_decorrelation_parameter`: Cloud overlap decorrelation parameter
check units - maybe a height?

2021-05-25 21:10 UTC, dudhia commented on Metadata-standard-names.md
> +* `time_integral_of_height_of_launch_level_of_orographic_gravity_wave`: Time integral of height of launch level of orographic gravity wave
based on units - may be a time average? Also others below

2021-05-25 21:13 UTC, dudhia commented on Metadata-standard-names.md
> +* `relative_variance_of_subgrid_cloud_condensate_distribution`: Relative variance of subgrid cloud condensate distribution
unit missing

2021-05-25 21:15 UTC, dudhia commented on Metadata-standard-names.md
> +* `tendency_of_y_momentum_due_to_blocking_drag`: Tendency of y momentum due to blocking drag
given units this may also be wind. Check below too.

2021-05-25 21:18 UTC, dudhia commented on Metadata-standard-names.md
> +* `accumulated_lwe_thickness_of_ice_amount_in_bucket`: Accumulated lwe thickness of ice amount in bucket
are these really different units from snow below?

2021-05-25 21:20 UTC, dudhia commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = m
I am surprised these would be m instead of mm

2021-05-25 21:23 UTC, dudhia commented on Metadata-standard-names.md
> +* `autoconversion_to_rain_coefficient`: Autoconversion to rain coefficient
these types of variables typically may have units, so this would likely be parametrization specific

2021-05-25 21:26 UTC, dudhia commented on Metadata-standard-names.md
> +* `cumulative_surface_downwelling_longwave_flux_multiplied_by_timestep`: Cumulative surface downwelling longwave flux multiplied by timestep
by timestep or by time?

2021-05-25 21:28 UTC, dudhia commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = W m-2 s
Instead of W m-2 s better to use J  m-2 for these

2021-05-25 21:29 UTC, dudhia commented on Metadata-standard-names.md
> +* `cumulative_transpiration_flux_multiplied_by_timestep`: Cumulative transpiration flux multiplied by timestep
time not in units?

2021-06-02 17:25 UTC, ligiabernardet commented on Metadata-standard-names.md
>  * `vertical_layer_index`: index of a particular vertical level
I propose we change 

- The longname for _vertical_layer_dimension_ from _number of vertical levels_ to _number of vertical layers_
- The longname for _vertical_layer_index_ from _index of a particular vertical level_ to index of a particular vertical layer

2021-06-02 17:32 UTC, gold2718 commented
I see a lot of standard names with the phrase, `timestep` and also many with `time_step`.
Should, could we standardize on one of these and use it consistently?
The rules seem to indicate that we should be using `timestep`.

2021-06-02 17:44 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `specific_heat_of_liquid_water_at_constant_pressure`: Specific heat of liquid water at constant pressure
Specific heat changes very slightly for liquids and solids. So _at_constant_pressure_ can be omitted from standard name and kept only in long name

2021-06-02 17:44 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `specific_heat_of_ice_at_constant_pressure`: Specific heat of ice at constant pressure
Specific heat changes very slightly for liquids and solids. So _at_constant_pressure_ can be omitted from standard name and kept only in long name

2021-06-02 17:46 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `surface_runoff_flux_in_m_sm1`: Surface runoff flux in m sm1
Agree. If changed for variable _surface_runoff_flux_in_m_sm1_, this should also be changed for variable _subsurface_runoff_flux_in_m_sm1_

2021-06-02 17:57 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `x_stress_due_to_gravity_wave_drag`: X stress due to gravity wave drag
I am seeking a recommendation from the GWD developer (Mike Toy)

2021-06-02 18:00 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `instantaneous_momentum_flux_due_to_turbulent_orographic_form_drag`: Instantaneous momentum flux due to turbulent orographic form drag
I am seeking a recommendation from the GWD developer (Mike Toy)

2021-06-02 18:01 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `bulk_richardson_number_at_lowest_model_level_over_water`: Bulk richardson number at lowest model level over water
Suggest changing to `bulk_richardson_number_at_lowest_model_layer_over_water`: Bulk richardson number at lowest model layer over water

2021-06-02 18:09 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `depth_of_soil_levels_for_land_surface_model`: Depth of soil levels for land surface model
I am seeking a recommendation from the RUC LSM developer (Tanya Smirnova)

2021-06-02 18:12 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `volume_mixing_ratio_co2`: Volume mixing ratio co2
Hmmm. In my experience volume mixing ratio is the number of moles of the gas divided by the number of moles of air. CF conventions list volume mixing ratio as unitless, which is compatible with what we have here (fraction)

2021-06-02 18:12 UTC, climbfuji commented on Metadata-standard-names.md
> +* `depth_of_soil_levels_for_land_surface_model`: Depth of soil levels for land surface model
Tanya is out for the entire month.

2021-06-03 22:22 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `x_stress_due_to_gravity_wave_drag`: X stress due to gravity wave drag
Mike Toy and Valery Yudin, developers of the GWD, recommend to keep this variable named as stress, which is defined as force per unit area (N/m2 = Pa). 
I realize that other variables called stress have units of m2/s2, and that we will need to explore further how resolve this.

2021-06-03 22:23 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `instantaneous_momentum_flux_due_to_turbulent_orographic_form_drag`: Instantaneous momentum flux due to turbulent orographic form drag
The recommendation from Mike Toy and Valery Yudin is to replace instantaneous_momentum_flux_due_to_* with instantaneous_momentum_flux_magnitude_due_to_*.

2021-06-03 22:27 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `depth_of_soil_levels_for_land_surface_model`: Depth of soil levels for land surface model
Siwei He, who also develops the RUC model, said it is not layers but levels (=interfaces). Given the terminology in the Rules #14, I suggest 
```suggestion
* `depth_of_soil_interfaces_for_land_surface_model`: Depth of soil interfaces for land surface model
```

2021-06-03 22:32 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `time_integral_of_height_of_launch_level_of_orographic_gravity_wave`: Time integral of height of launch level of orographic gravity wave
According to Mike Toy and Valery Yudin, this is indeed a time average. (need to fix in various places)
```suggestion
* `time_averaged_launch_height_for_orographic_gravity_waves`: Time-averaged launch height for orographic gravity waves
```

2021-06-03 22:43 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `relative_variance_of_subgrid_cloud_condensate_distribution`: Relative variance of subgrid cloud condensate distribution
Technically this is correct because it should be the square(variance) of kg kg-1. Do you suggest kg2 kg-2?

2021-06-03 22:52 UTC, ligiabernardet commented
Should be timestep (not time step)

> I see a lot of standard names with the phrase, `timestep` and also many with `time_step`.
> Should, could we standardize on one of these and use it consistently?
> The rules seem to indicate that we should be using `timestep`.

2021-06-03 22:53 UTC, ligiabernardet commented on Metadata-standard-names.md
> +* `cumulative_surface_downwelling_longwave_flux_multiplied_by_timestep`: Cumulative surface downwelling longwave flux multiplied by timestep
by timestep

2021-06-03 22:55 UTC, ligiabernardet commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = W m-2 s
J m-2 is fine (need to change in various places)

2021-06-04 17:55 UTC, dudhia commented on Metadata-standard-names.md
> +* `volume_mixing_ratio_co2`: Volume mixing ratio co2
yes, here we have kg kg-1 which I question, also many others below

2021-06-08 21:52 UTC, cacraigucar commented on Metadata-standard-names.md
>  * `vertical_layer_index`: index of a particular vertical level
If we change "vertical_layer_dimension" then we probably need to change "horizontal_dimension" and "vertical_interface_dimension" as well.  @ligiabernardet - are you implying these changes also?

2021-06-08 21:52 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `vertical_index_at_surface_adjacent_layer`: Vertical index at surface adjacent layer
Thanks for the explanation.  Keeping "vertical" is fine.

2021-06-09 16:06 UTC, grantfirl commented
> I see a lot of standard names with the phrase, `timestep` and also many with `time_step`.
> Should, could we standardize on one of these and use it consistently?
> The rules seem to indicate that we should be using `timestep`.

Yes. Unfortunately, we are doing this exercise with ~1/3 of names not having been "processed" for consistency, which makes this very messy.

2021-06-09 16:30 UTC, grantfirl commented
During yesterday's ccpp-framework meeting, it was discussed to either 1) leave units off of the standard name list or 2) have a list of units. Regarding the first choice, even though CF includes "canonical units" for each name, it doesn't mean that we have to follow suit, since the CCPP should have unit conversion capability. Deciding on "canonical units" can be yet another conflict point among scientists engaging in this effort and is largely subjective preference, so NOT having units is a way of "punting" on this problem. @dudhia finds that having units can be helpful (at least for the initial standard name decision process), so it was also suggested potentially having a list. To be maximally useful, such a list should be the set of "permissible" units (i.e. those that have conversions defined in the framework).

Since the number of conversions defined is currently small and adds additional complexity, IMO, I would propose to remove units at this time and to add an issue in this repository to revisit the unit list concept when the names are further along. Any thoughts? @ligiabernardet @dudhia @gold2718 @cacraigucar @climbfuji

2021-06-09 19:16 UTC, dudhia commented
Yes, units are very helpful for making sure you're on the same page with
the verbal description.
My example was that there have been mixed uses of heat flux which I noted
in the standard names document.
I agree that they should be more for informational purposes than some kind
of enforcement.

On Wed, Jun 9, 2021 at 10:30 AM grantfirl ***@***.***> wrote:

> During yesterday's ccpp-framework meeting, it was discussed to either 1)
> leave units off of the standard name list or 2) have a list of units.
> Regarding the first choice, even though CF includes "canonical units" for
> each name, it doesn't mean that we have to follow suit, since the CCPP
> should have unit conversion capability. Deciding on "canonical units" can
> be yet another conflict point among scientists engaging in this effort and
> is largely subjective preference, so NOT having units is a way of "punting"
> on this problem. @dudhia <https://github.com/dudhia> finds that having
> units can be helpful (at least for the initial standard name decision
> process), so it was also suggested potentially having a list. To be
> maximally useful, such a list should be the set of "permissible" units
> (i.e. those that have conversions defined in the framework).
>
> Since the number of conversions defined is currently small and adds
> additional complexity, IMO, I would propose to remove units at this time
> and to add an issue in this repository to revisit the unit list concept
> when the names are further along. Any thoughts? @ligiabernardet
> <https://github.com/ligiabernardet> @dudhia <https://github.com/dudhia>
> @gold2718 <https://github.com/gold2718> @cacraigucar
> <https://github.com/cacraigucar> @climbfuji <https://github.com/climbfuji>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-857851128>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77DFO44PHBZQFPLH4FDTR6JKHANCNFSM44IFYSVA>
> .
>

2021-06-09 19:19 UTC, dudhia commented
I think that timestep is fine. It used to trigger spell checkers, but now
it seems it doesn't.

On Wed, Jun 9, 2021 at 10:06 AM grantfirl ***@***.***> wrote:

> I see a lot of standard names with the phrase, timestep and also many
> with time_step.
> Should, could we standardize on one of these and use it consistently?
> The rules seem to indicate that we should be using timestep.
>
> Yes. Unfortunately, we are doing this exercise with ~1/3 of names not
> having been "processed" for consistency, which makes this very messy.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-857834544>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77DOPXH6M3FXPXRFPZDTR6GR5ANCNFSM44IFYSVA>
> .
>

2021-06-23 22:07 UTC, grantfirl commented
@climbfuji @cacraigucar @dudhia @gold2718 @ligiabernardet @bluefinweiwei The standard_names.xml and associated markdown files have been changed pretty significantly again, although the new standard names and changes are mostly the same as the previous version, just with comments addressed. The big changes were in organization (rather than having one "uncategorized" section, for the purposes of this PR, I organized the names by GFS DDT and alphabetized them) and removal of standard names that have not been "processed" completely on our side (interstitial and diagnostic variables). IMO, this makes it more useful for the spreadsheet that we've been working off of and it makes it usable for a new script that I wrote (standard_name_helper.py -- which can be added in a new PR if desired). Since the XML/MD changed so much with the latest commit, previous comments in this PR will mostly be outdated. I'll do my best to respond to them one by one. Some comments will effectively be "abandoned" because they referred to standard names from the interstitial/diag DDTs that have been temporarily removed from the dictionary, but I took note of these (since Jimy kindly took the time to review) and they can be addressed in a future PR when those names are added.

2021-06-23 22:09 UTC, grantfirl commented on Metadata-standard-names.md
> +* `vertical_dimension_plus_one`: number of vertical levels + 1
This has been addressed. It is now 'vertical_interface_dimension'. It now also says 'layers' instead of levels in the long name.

2021-06-23 22:11 UTC, grantfirl commented on Metadata-standard-names.md
> +* `tendency_of_air_temperature_due_to_X`: Change in temperature from a parameterization
I removed the "due_to_X" changes because, as @gold2718 pointed out, it was referring to the heuristic and not an actual standard name.

2021-06-23 22:14 UTC, grantfirl commented on Metadata-standard-names.md
> +* `tendency_of_air_temperature_due_to_model_physics`: Total change in temperature from a                               physics suite
`tendency_of_air_temperature_due_to_model_physics` is also in CF.

2021-06-23 22:21 UTC, grantfirl commented on Metadata-standard-names.md
>  * `vertical_layer_index`: index of a particular vertical level
level was removed from the long names entirely, with the exception of "sea_level" which is a well-defined concept independent of our layer/interface convention.

2021-06-23 22:21 UTC, grantfirl commented on Metadata-standard-names.md
> +* `flag_for_generic_tendency_due_to_plantary_boundary_layer`: Flag for generic tendency due to plantary boundary layer
Fixed.

2021-06-23 22:25 UTC, grantfirl commented on Metadata-standard-names.md
> +* `kinematic_surface_upward_sensible_heat_flux_reduced_by_surface_roughness`: Kinematic surface upward sensible heat flux reduced by surface roughness
I'm not sure I understand. Potential temperature and temperature both have the same units. In the UFS physics, this is corresponding to [w'T'] rather than rho*cp*[w'T']. I've heard this referred to as the "kinematic sensible heat flux" as opposed to just "sensible heat flux", which is typically in W m-2. I could see calling it "surface_upward_temperature_flux..." I suppose, though.

2021-06-23 22:26 UTC, grantfirl commented on Metadata-standard-names.md
> +* `kinematic_surface_upward_latent_heat_flux_reduced_by_surface_roughness`: Kinematic surface upward latent heat flux reduced by surface roughness
Same comment. If "kinematic_latent_heat_flux..." will not be understood, we could change to "surface_upward_specific_humidity_flux..."

2021-06-23 22:28 UTC, grantfirl commented on Metadata-standard-names.md
> +* `specific_heat_of_liquid_water_at_constant_pressure`: Specific heat of liquid water at constant pressure
We haven't processed most of the physical constants yet (and this was removed from the XML), but I took note to address this in a future PR.

2021-06-23 22:28 UTC, grantfirl commented on Metadata-standard-names.md
> +* `specific_heat_of_ice_at_constant_pressure`: Specific heat of ice at constant pressure
We haven't processed most of the physical constants yet (and this was removed from the XML), but I took note to address this in a future PR.

2021-06-23 22:29 UTC, grantfirl commented on Metadata-standard-names.md
> +* `surface_runoff_flux_in_m_sm1`: Surface runoff flux in m sm1
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:29 UTC, grantfirl commented on Metadata-standard-names.md
> +* `x_stress_due_to_gravity_wave_drag`: X stress due to gravity wave drag
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:30 UTC, grantfirl commented on Metadata-standard-names.md
> +* `instantaneous_momentum_flux_due_to_turbulent_orographic_form_drag`: Instantaneous momentum flux due to turbulent orographic form drag
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:31 UTC, grantfirl commented on Metadata-standard-names.md
> +* `kinematic_surface_upward_sensible_heat_flux`: Kinematic surface upward sensible heat flux
Same comment RE: "kinematic" wording, but it doesn't have to be potential temperature (could be [w'T'])

2021-06-23 22:31 UTC, grantfirl commented on Metadata-standard-names.md
> +* `bulk_richardson_number_at_lowest_model_level_over_water`: Bulk richardson number at lowest model level over water
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:32 UTC, grantfirl commented on Metadata-standard-names.md
> +* `kinematic_surface_upward_latent_heat_flux`: Kinematic surface upward latent heat flux
Same comment RE: kinematic wording. Can change if necessary.

2021-06-23 22:35 UTC, grantfirl commented on Metadata-standard-names.md
> +* `depth_of_soil_levels_for_land_surface_model`: Depth of soil levels for land surface model
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR. There was a similar variable called `thickness_of_soil_levels_for_land_surface_model`. In this case, I changed to "layers" since it is referring to the distance between interfaces. But, the one listed should definitely be interfaces if that is what the depth is referring to. Noted for future.

2021-06-23 22:38 UTC, grantfirl commented on Metadata-standard-names.md
> +* `volume_mixing_ratio_co2`: Volume mixing ratio co2
I left the units as-is. These variables were added to the dictionary by CGD folks and they happen to have the same units as the identical variables that are in the UFS (they are used in RRTMGP). It doesn't mean that it's right, just that it was the same coming from two directions.

2021-06-23 22:40 UTC, grantfirl commented on Metadata-standard-names.md
> +* `cloud_overlap_decorrelation_parameter`: Cloud overlap decorrelation parameter
In this case, I don't think it is referring to a decorrelation length. IIRC, this variable was added by the scheme author, so I'm inclined not to change it. I'm assuming that if someone is wanting to pass around a decorrelation length that it will be a different, distinct variable.

2021-06-23 22:42 UTC, grantfirl commented on Metadata-standard-names.md
> +* `time_integral_of_height_of_launch_level_of_orographic_gravity_wave`: Time integral of height of launch level of orographic gravity wave
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:42 UTC, grantfirl commented on Metadata-standard-names.md
> +* `relative_variance_of_subgrid_cloud_condensate_distribution`: Relative variance of subgrid cloud condensate distribution
Added kg2 kg-2 in the dictionary XML (but did not change in the actual metadata yet).

2021-06-23 22:43 UTC, grantfirl commented on Metadata-standard-names.md
> +* `tendency_of_y_momentum_due_to_blocking_drag`: Tendency of y momentum due to blocking drag
Yes, it would be good to differentiate 'momentum' from 'wind'. This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:44 UTC, grantfirl commented on Metadata-standard-names.md
> +* `accumulated_lwe_thickness_of_ice_amount_in_bucket`: Accumulated lwe thickness of ice amount in bucket
Can check units in the future PR. This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:45 UTC, grantfirl commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = m
For the purposes of this dictionary, simple length units are pretty arbitrary. There are already conversions between mm and m when units differ amongst host/physics metadata in the ccpp-framework.

2021-06-23 22:46 UTC, grantfirl commented on Metadata-standard-names.md
> +* `autoconversion_to_rain_coefficient`: Autoconversion to rain coefficient
I didn't check to see if this variable has some kind of unit in the code. I'm guessing it was checked at some time?

2021-06-23 22:52 UTC, grantfirl commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = W m-2 s
Changed in the dictionary (all of them), but not the actual metadata yet. I think that units were written that way because the code takes a variable in W m-2 and multiples by the timestep. This facilitates time-averaging that is done outside of the physics in the UFS. It's going to be difficult to enforce any kind of units convention, whether J s-1 or W is acceptable, etc. Seeing W m-2 s is kinda grating, though, when one knows that W = J s-1 and W s is so easily reduced.

2021-06-23 22:54 UTC, grantfirl commented on Metadata-standard-names.md
> +* `cumulative_transpiration_flux_multiplied_by_timestep`: Cumulative transpiration flux multiplied by timestep
This was removed from the XML since it was unprocessed in the interstitial DDT. I took note to change in a future PR.

2021-06-23 22:55 UTC, grantfirl commented
> Should be timestep (not time step)
> 
> > I see a lot of standard names with the phrase, `timestep` and also many with `time_step`.
> > Should, could we standardize on one of these and use it consistently?
> > The rules seem to indicate that we should be using `timestep`.

Darn it, I missed this comment. There are still a couple variables with "time_step" instead of "timestep". Will change.

2021-06-24 20:47 UTC, grantfirl commented
> > Should be timestep (not time step)
> > > I see a lot of standard names with the phrase, `timestep` and also many with `time_step`.
> > > Should, could we standardize on one of these and use it consistently?
> > > The rules seem to indicate that we should be using `timestep`.
> 
> Darn it, I missed this comment. There are still a couple variables with "time_step" instead of "timestep". Will change.

time_step -> timestep has been made consistent in the XML/md with the latest commit.

2021-06-24 21:01 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `vertical_layer_index`: index of a particular vertical layer
I can't find where this was discussed in the conversations (too many are hidden from a search).  Seeing these two standard names side by side (vertical_dimension and vertical_layer_index), I feel like they should be consistent.  I also feel like vertical_layer_dimension is a more explicit name and pairs nicely with vertical_interface_dimension.  There is no need to remember which flavor is meant without the qualifier.

2021-06-24 21:36 UTC, grantfirl commented on Metadata-standard-names.md
> +* `vertical_layer_index`: index of a particular vertical layer
I see what you're saying. We have the implicit rule that all variables with vertical extent are assumed to be on layers by default (and therefore do not have "layer" in their name). But this variable still has "layer" in it. You're proposing that 1) we either make an exception to the implicit layer rule and have "vertical_layer_dimension" to match "vertical_layer index" (and "vertical_interface_dimension/index") or 2) change "vertical_layer_index" to "vertical_index". It sounds like @cacraigucar prefers 1 for symmetry. I would probably prefer 2 to adhere to the rules better, but I don't feel particularly strongly (other than that we may need to add a caveat to the rules so people don't complain). Either way, something should change. Any other views? @ligiabernardet @gold2718

2021-06-24 21:40 UTC, grantfirl commented on Metadata-standard-names.md
> +* `vertical_layer_index`: index of a particular vertical layer
Also, @cacraigucar apologies for hiding comments -- trying to streamline resolved discussions a bit. I think the previous one was about consistency with removing "level", which I did in the XML, so I thought it was resolved.

2021-06-24 22:06 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `vertical_layer_index`: index of a particular vertical layer
@grantfirl - No apologies needed.  It could just be as easily "github" hiding conversations as well.  This is just one of the annoying "features" of github.  Resolving conversations is the only way to keep track of what  is still important.

2021-06-24 23:26 UTC, gold2718 reviewed
A few more comments / questions

2021-06-24 23:26 UTC, gold2718 commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
By this rule, shouldn't `reference_pressure` (or possibly `reference_air_pressure`) be `reference_pressure_at_interface`? I worry that strict adherence to this 'rule' could create ambiguous standard names.

2021-06-25 16:00 UTC, grantfirl commented on Metadata-standard-names.md
> +* `vertical_layer_index`: index of a particular vertical layer
OK, I'll make the change "vertical_dimension" -> "vertical_layer_dimension" (or more accurately, reinstate the original).

2021-06-25 16:05 UTC, grantfirl commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
Thanks. I am definitely confused by all of different "reference..." variables. If I change this one back, we'll then have "reference_pressure", "reference_surface_air_pressure_for_atmosphere_vertical_coordinate", "surface_reference_air_pressure", all of which semantically mean the same thing to me. It is highly likely that I'm just being ignorant here.

2021-06-25 16:09 UTC, grantfirl commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
The fact that "reference_pressure" should be an array with vertical extent is news to me. In your previous comment,  the description in the CF standard of "reference_pressure" is "A constant pressure value, typically representative of mean sea level pressure...".

2021-06-25 16:10 UTC, grantfirl commented on Metadata-standard-names.md
> +* `dimensionless_exner_function`: exner function
Or, did you mean at one particular interface, e.g. reference_pressure_at_surface_interface?

2021-07-01 20:01 UTC, grantfirl commented
I added an issue to revisit the reference pressure issue at some point in the future: https://github.com/ESCOMP/CCPPStandardNames/issues/15

2021-07-01 20:04 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
There are three distinct variables that CAM is using currently.  The names are probably wrong.  If you would like to delete the "reference_surface_air_pressure_for_atmosphere_vertical_coordinate" and "surface_reference_air_pressure",  feel free to do so.  We will open a PR with all of our variables which we need to introduce as we get our physics migrated.  During that process, I believe we will probably end up renaming these variables.  They may become CAM only names which may not even be stored in the github repo.

2021-07-01 20:08 UTC, grantfirl commented on Metadata-standard-names.md
> +* `reference_air_pressure`: reference pressure
For this PR, I left all of these alone. It doesn't have any bearing on NOAA code at the moment, but we should strive for consistency in the future. I'll add a synopsis of Adam and Andy's comments on issue #15

2021-07-01 20:10 UTC, grantfirl commented on Metadata-standard-names.md
> +* `kinematic_surface_upward_sensible_heat_flux_reduced_by_surface_roughness`: Kinematic surface upward sensible heat flux reduced by surface roughness
@dudhia The "kinematic" variables have been updated to surface_upward_specific_humidity_flux and surface_upward_temperature_flux.

2021-07-01 20:10 UTC, grantfirl commented on Metadata-standard-names.md
> +* `kinematic_surface_upward_latent_heat_flux_reduced_by_surface_roughness`: Kinematic surface upward latent heat flux reduced by surface roughness
This has been changed too.

2021-07-01 20:11 UTC, grantfirl commented on check_xml_unique.py
> +#!/usr/bin/env python
Fixed.

2021-07-13 23:08 UTC, cacraigucar approved these changes
Thanks - I confirmed all of my requests have been addressed one way or the other.

2021-07-14 20:52 UTC, cacraigucar commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = index
While reviewing #14, I looked back to find out how  `real` is being used.  An index being a real number feels "wrong" to me.   Should it not be an integer?  If it is truly needs to have non-integer gradients, then it isn't an index.

2021-07-20 20:12 UTC, climbfuji approved these changes

2021-07-23 03:31 UTC, ligiabernardet approved these changes

2021-07-28 04:24 UTC, gold2718 requested changes
Please hit the re-review button when changes are complete.
I think adding the new rules can be added to this PR.

2021-07-28 12:43 UTC, climbfuji commented on standard_names.xml
> +    <standard_name name="specific_humidity">
@grantfirl @ligiabernardet We should also correct the units in cpp-physics, fv3atm and scm, or?

2021-07-29 03:32 UTC, gold2718 requested changes
I would still like to understand the rules around these standard names. For instance, these names begin with `volume_mixing_ratio_`. However, other standard names use `volumetric` instead (e.g., 
`volumetric_equilibrium_soil_moisture`). Is there a reason to choose one over the other? Can we always use one? Please add one or more rules (to StandardNamesRules.rst) to clarify this usage (and that mixing ratios are mass mixing ratios by default or whatever the true default rule is).
Also, I still think that we need to specify whether a mixing ratio is wet or dry. The mixing ratios in this PR do not specify either, that should be corrected. This is of critical importance for interoperability. Please add a rule for this and follow that rule for mixing ratios in this PR.

2021-07-29 15:22 UTC, dudhia commented
Regarding volumetric versus volume, we need to use what is in most use in
those areas of science.
Volumetric for sure is what the land people use for soil moisture, but
might sound strange to radiation people.

On Wed, Jul 28, 2021 at 9:32 PM goldy ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I would still like to understand the rules around these standard names.
> For instance, these names begin with volume_mixing_ratio_. However, other
> standard names use volumetric instead (e.g.,
> volumetric_equilibrium_soil_moisture). Is there a reason to choose one
> over the other? Can we always use one? Please add one or more rules (to
> StandardNamesRules.rst) to clarify this usage (and that mixing ratios are
> mass mixing ratios by default or whatever the true default rule is).
> Also, I still think that we need to specify whether a mixing ratio is wet
> or dry. The mixing ratios in this PR do not specify either, that should be
> corrected. This is of critical importance for interoperability. Please add
> a rule for this and follow that rule for mixing ratios in this PR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#pullrequestreview-717636995>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77GUPXCNZQM3IS3NEPDT2DDWTANCNFSM44IFYSVA>
> .
>

2021-07-29 15:50 UTC, gold2718 commented
> Regarding volumetric versus volume, we need to use what is in most use in those areas of science. Volumetric for sure is what the land people use for soil moisture, but might sound strange to radiation people.

I see your point, however, one of the rules is to follow CF conventions and while the current uses of `volumetric` do not have analogs in the CF table (as far as I can tell), CF does not use the term, `volumetric` even for land terms (e.g., `volume_fraction_of_condensed_water_in_soil_at_wilting_point`).

2021-07-29 15:51 UTC, gold2718 commented on standard_names.xml
> +    <standard_name name="rain_mixing_ratio">
I would prefer the term, `mass` included here (e.g., `mass_mixing_ratio_of_rain`, which is consistent with the way the volume mixing ratio standard names are constructed). However, even if it is decided that mass mixing ratio is the default, please include the term, 'mass mixing ratio' in a custom `long_name` property for these quantities.

2021-07-29 15:52 UTC, dudhia commented
CF should have a description for soil moisture which is conventionally
volumetric, but maybe they leave the word out.

On Thu, Jul 29, 2021 at 9:50 AM goldy ***@***.***> wrote:

> Regarding volumetric versus volume, we need to use what is in most use in
> those areas of science. Volumetric for sure is what the land people use for
> soil moisture, but might sound strange to radiation people.
>
> I see your point, however, one of the rules is to follow CF conventions
> and while the current uses of volumetric do not have analogs in the CF
> table (as far as I can tell), CF does not use the term, volumetric even
> for land terms (e.g.,
> volume_fraction_of_condensed_water_in_soil_at_wilting_point).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-889260939>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77HKCMX3K5YD5Q227U3T2F2ETANCNFSM44IFYSVA>
> .
>

2021-07-29 15:56 UTC, dudhia commented
so alternative names here might be dry_mass_mixing_ratio and
moist_mass_mixing_ratio

On Thu, Jul 29, 2021 at 9:51 AM goldy ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In standard_names.xml
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#discussion_r679278116>
> :
>
> > @@ -362,48 +362,48 @@
>                     long_name="Ratio of the mass of ice to the mass of dry air">
>        <type kind="kind_phys" units="kg kg-1">real</type>
>      </standard_name>
> -    <standard_name name="rain_water_mixing_ratio">
> +    <standard_name name="rain_mixing_ratio">
>
> I would prefer the term, mass included here (e.g.,
> mass_mixing_ratio_of_rain, which is consistent with the way the volume
> mixing ratio standard names are constructed). However, even if it is
> decided that mass mixing ratio is the default, please include the term,
> 'mass mixing ratio' in a custom long_name property for these quantities.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#pullrequestreview-718264080>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77A4CRF2QPJF66WR3P3T2F2HFANCNFSM44IFYSVA>
> .
>

2021-07-29 16:43 UTC, gold2718 commented
> CF should have a description for soil moisture which is conventionally volumetric, but maybe they leave the word out.

Searching for the combination of "soil" and "moisture" does not turn up any volumetric terms, only mass fraction terms and "moisture_content" terms which are `kg m-2`.

2021-07-29 16:47 UTC, gold2718 commented
> so alternative names here might be dry_mass_mixing_ratio and moist_mass_mixing_ratio

Or `mass_mixing_ratio_of_<x>_dry_air` (similar to `surface_pressure_of_dry_air` which is already in the dictionary) and `mass_mixing_ratio_of_<x>_of_moist_air`.

2021-07-29 16:49 UTC, climbfuji commented
> so alternative names here might be dry_mass_mixing_ratio and moist_mass_mixing_ratio
> […](#)

It's more complicated with that, because `moist_mass_mixing_ratio` will require additional qualifiers like `with_respect_to`. Moist mixing ratios can be with respect to just specific humidity, or all hydrometeors, ...

2021-07-29 16:55 UTC, dudhia commented
maybe mass_mixing_ratio_of_*_with_respect_to_moist_mass ?
Is mass_mixing_ratio an accepted term? Maybe the first mass is redundant
because it is implied in mixing_ratio.

On Thu, Jul 29, 2021 at 10:50 AM Dom Heinzeller ***@***.***>
wrote:

> so alternative names here might be dry_mass_mixing_ratio and
> moist_mass_mixing_ratio
> … <#m_6197343537365292180_>
>
> It's more complicated with that, because moist_mass_mixing_ratio will
> require additional qualifiers like with_respect_to. Moist mixing ratios
> can be with respect to just specific humidity, or all hydrometeors, ...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-889303893>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77CEACMWJ7UMQH4TWV3T2GBDVANCNFSM44IFYSVA>
> .
>

2021-07-30 18:25 UTC, ligiabernardet commented
Pls see proposed rules clarification in https://github.com/ESCOMP/CCPPStandardNames/pull/16. Once we agree on the rules, we can make changes in the names listed in this PR.

2021-07-30 21:55 UTC, gold2718 commented on standard_names.xml
> +      </standard_name>
Names such as this seem to be host-model specific. Are they needed for interoperability? If not, please remove them as they just make it harder to find standard names used in physics schemes.
If this somehow is to be used in physics schemes, please document its usage in the rules document.

2021-08-06 15:58 UTC, grantfirl commented
@gold2718 @cacraigucar Since "constituent_mixing_ratio" originally came from you all, and according to the latest rule change regarding "mixing_ratio", should we add ...wrt_dry_air, wrt_moist_air, wrt_total_mass to this standard name?

2021-08-06 15:59 UTC, cacraigucar commented
> @gold2718 @cacraigucar Since "constituent_mixing_ratio" originally came from you all, and according to the latest rule change regarding "mixing_ratio", should we add ...wrt_dry_air, wrt_moist_air, wrt_total_mass to this standard name?

I will defer to @gold2718 on this one.

2021-08-06 16:23 UTC, grantfirl commented
@ligiabernardet @bluefinweiwei The e97a517 commit from @bluefinweiwei changed the volume_mixing_ratio units from kg kg-1 to m3 m-3. The rules now state that they should be in mol mol-1, so this needs to be reflected in this PR (undoing commit e97a517), right?

2021-08-06 16:24 UTC, ligiabernardet commented
Yes. We had switched to m3 m-3, but now have settled on mol mol-1.

On Fri, Aug 6, 2021 at 10:23 AM grantfirl ***@***.***> wrote:

> @ligiabernardet <https://github.com/ligiabernardet> @bluefinweiwei
> <https://github.com/bluefinweiwei> The e97a517 commit from @bluefinweiwei
> <https://github.com/bluefinweiwei> changed the volume_mixing_ratio units
> from kg kg-1 to m3 m-3. The rules now state that they should be in mol
> mol-1, so this needs to be reflected in this PR (undoing commit e97a517),
> right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-894372009>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE7WQAVZSVPRBJDQ43CVUZTT3QEAPANCNFSM44IFYSVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-06 16:32 UTC, gold2718 commented
@grantfirl, @cacraigucar,
> Since "constituent_mixing_ratio" originally came from you all, and according to the latest rule change regarding "mixing_ratio", should we add ...wrt_dry_air, wrt_moist_air, wrt_total_mass to this standard name?

Since the array can contain a mix of all these plus number concentration fields, how about just `constituents_array`?
Or, maybe we should take this out entirely since there is no way it will ever be fixed (e.g., different chemistry suite will have different constituents). Given the CCPP principle that two objects with the same standard name represent the same physical quantity, this feels like something that should not be listed.

Since we do need something to transport arrays of these items around, maybe we should have `constituent_array` with all the usual rules for mixing ratios. I feel this would work because chemistry suites normally keep all of their constituents in the same form (e.g., `volume_mixing_ratio_wrt_total_mass`) so the only thing that would vary is the number (and type) of species.

2021-08-06 16:33 UTC, grantfirl commented
@ligiabernardet Thanks for the confirmation. I'm working on updating this PR as discussed yesterday now. There will be a PR into @bluefinweiwei's fork to inspect at some point, whose changes will get transferred to this PR once approved/merged. As far as updating ccpp-physics and hosts with these further changes, do we want to do that right away? Pro: can maintain consistency with the CCPPStandardNames repo; Con: more PRs to have to test and potentially annoy reviewers.

2021-08-06 16:55 UTC, ligiabernardet commented
My recommendation is to wait until we reach agreement wrt this PR13 and later proceed to updating ccpp-physics and fv3atm. We do need to reduce the number of standard-name related updates to ccpp-physics and fv3atm to reduce the burden on reviewers.

2021-08-06 17:00 UTC, ligiabernardet commented on standard_names.xml
> +      </standard_name>
@goldy DTC is working on making updates to this PR for consistency with the rules. We had a lengthy internal discussion yesterday regarding how to handle host-specific variables. And we also discussed keeping track of which schemes are using which standard names (some names are scheme specific). We think it is important for us to have a complete dictionary of variables, even host specific ones. But we can identify the host-specific names in some way, such as with metadata or by keeping them in a branch. We think this requires more discussion than what we can have via comments in this PR. I would like to propose that we accept/merge this PR as is (with host-specific variables) and then follow up with a discussion on how to best tackle this. If you agree, one of us can open an issue to make sure we don't forget and continue working on this topic.

2021-08-06 17:01 UTC, grantfirl commented
> @grantfirl, @cacraigucar,
> 
> > Since "constituent_mixing_ratio" originally came from you all, and according to the latest rule change regarding "mixing_ratio", should we add ...wrt_dry_air, wrt_moist_air, wrt_total_mass to this standard name?
> 
> Since the array can contain a mix of all these plus number concentration fields, how about just `constituents_array`?
> Or, maybe we should take this out entirely since there is no way it will ever be fixed (e.g., different chemistry suite will have different constituents). Given the CCPP principle that two objects with the same standard name represent the same physical quantity, this feels like something that should not be listed.
> 
> Since we do need something to transport arrays of these items around, maybe we should have `constituent_array` with all the usual rules for mixing ratios. I feel this would work because chemistry suites normally keep all of their constituents in the same form (e.g., `volume_mixing_ratio_wrt_total_mass`) so the only thing that would vary is the number (and type) of species.

Another wrinkle is that NOAA models have "tracer_concentration" to refer to the same array as the current "constituent_mixing_ratio". These should probably be combined for better portability between hosts. CF doesn't mention "constituent" but does "tracer".

As you mentioned, I don't think that we can just get rid of the array since hosts/physics will want to use something like this. "Array" in "constituent_array" is redundant since dimensions are included in the metadata.

I see a couple of options:
1. Use an umbrella term like "constituent_concentration" or "tracer_concentration" as a catch-all for whatever the host/physics is using.
2. Have several different standard names/variables for different denominators, e.g. "tracer_concentration_wrt_moist_air" + "tracer_concentration_wrt_dry_air" + "tracer_concentration_wrt_total_mass".

1 is probably simpler in terms of coding, but makes the code function more ambiguous IMO (actual denominators in the variables are effectively hidden unless documented elsewhere). 2 is probably more work but is more explicit. It also has the benefit of making it obvious when a physics scheme expects one denominator and the host is providing something else.

2021-08-06 17:17 UTC, gold2718 commented
> 
    Use an umbrella term like "constituent_concentration" or "tracer_concentration" as a catch-all for whatever the host/physics is using.
    Have several different standard names/variables for different denominators, e.g. "tracer_concentration_wrt_moist_air" + "tracer_concentration_wrt_dry_air" + "tracer_concentration_wrt_total_mass".

I have a strong preference for 2 as that is the only way we will ever be able to provide checking and (possibly automated) translation. We have had errors in simulations traced to a misunderstanding of whether a particular field was 'wet' or 'dry'.

2021-08-06 20:14 UTC, dudhia commented
Yes, this was discussed earlier and the wrt qualifiers are needed and hence
the rule was made explicit about that (Grant was not here for that).
Regarding tracer versus constituent. I think of tracers as passive and
constituents as possibly chemical species or something that can change.
So in my thinking constituents would always have species names
associated with them.

On Fri, Aug 6, 2021 at 11:17 AM goldy ***@***.***> wrote:

> Use an umbrella term like "constituent_concentration" or "tracer_concentration" as a catch-all for whatever the host/physics is using.
> Have several different standard names/variables for different denominators, e.g. "tracer_concentration_wrt_moist_air" + "tracer_concentration_wrt_dry_air" + "tracer_concentration_wrt_total_mass".
>
> I have a strong preference for 2 as that is the only way we will ever be
> able to provide checking and (possibly automated) translation. We have had
> errors in simulations traced to a misunderstanding of whether a particular
> field was 'wet' or 'dry'.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-894401435>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77B4IOL4V7BBGN2PAO3T3QKKZANCNFSM44IFYSVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-06 21:17 UTC, grantfirl commented
I also agree with the connotations of tracer vs. constituent. The problem on the NOAA side is that one array is used for both what we would consider atmospheric constituents (which can be described as proper concentrations with common denominators) and passive tracers that are either advected or not by the dycore depending on flags (e.g. cloud fraction, TKE). One could argue about whether the non-constituent components belong in this array, but we cannot necessarily dictate this by considering what would make our CCPP standard names more self-consistent. I believe that for the "tracer_concentration" variable that NOAA models are using, the only "true" relationship amongst the components is that they are potentially advected by the dycore.

@goldy For the constituent_mixing_ratio, I'm guessing that this isn't necessarily the case (and that advected variables are handled differently)? That is, we could not both agree to use something like "potentially_advected_species"?

It still seems like there should be space to combine these into one for better portability, especially since >90% of the variables in NOAA's "tracer_concentration" array are likely actual atmospheric constituents.

I don't know that we would be any worse off (in terms of code understandability) if we did the following:

1. Create 3 constituent variables/standard names to represent arrays with common denominators: constituent_mixing_ratio becomes one of constituent_mixing_ratio_wrt_moist_air/constituent_mixing_ratio_wrt_dry_air/constituent_mixing_ratio_wrt_total mass
2. Change NOAA's "tracer_concentration" variable to use the new constituent_mixing_ratio_wrt_moist_air, but it will just have stuff like TKE and cloud_fraction still tacked on to the end?

Any better ideas? I can't finish updating this PR with respect to mixing ratios until this is decided.

@ligiabernardet @dudhia @gold2718

2021-08-06 21:39 UTC, ligiabernardet commented
@grantfirl I appreciate the challenge here. I have not come up with a reasonable suggestion yet. This topic require discussion in person, perhaps on Tuesday's CCPP Framework meeting.It would be good to get an opinion from @climbfuji when he is back. 

The tracer concentration is already problematic as is, since it has units of kg kg-1 but some of the contents of the array are cloud fraction and TKE. However, calling it _mixing_ratio_of_ and keeping the TKE and cloud fraction in it is hard to justify.

2021-08-20 22:29 UTC, cacraigucar commented
> Why units of none instead of index like the other control variables?

As I said in #20, I am fine with this not being units=index since the values are floating point numbers.  I think index should just be for integers.  

Does that mean that the few standard names with have "_real" attached to them should also have their units changed?    See soil_type_classification_real for an example of one of these variables.

2021-08-20 23:40 UTC, dudhia commented
Yes, I agree, these are really categories not indices and perhaps the unit
should be category.
The code is unusual in expecting the category to be real, but that is a
separate issue.
Index should be used only for integers that can be an index in an array.

On Fri, Aug 20, 2021 at 4:29 PM cacraigucar ***@***.***>
wrote:

> Why units of none instead of index like the other control variables?
>
> As I said in #20 <https://github.com/ESCOMP/CCPPStandardNames/pull/20>, I
> am fine with this not being units=index since the values are floating point
> numbers. I think index should just be for integers.
>
> Does that mean that the few standard names with have "_real" attached to
> them should also have their units changed? See
> soil_type_classification_real for an example of one of these variables.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#issuecomment-902989666>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77DC5WSLUMUVPUV3REDT53JNBANCNFSM44IFYSVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-21 22:57 UTC, gold2718 commented
> Index should be used only for integers that can be an index in an array.

I like this statement, it should be in the rules (do we need a separate document for rules on units?).

2021-08-23 14:43 UTC, climbfuji commented
> > Index should be used only for integers that can be an index in an array.
> 
> I like this statement, it should be in the rules (do we need a separate document for rules on units?).

@gold2718 how about this: https://github.com/ESCOMP/CCPPStandardNames/pull/21

2021-08-24 02:09 UTC, ligiabernardet approved these changes
Thank you @grantfirl for addressing several of the previous comments and concerns including:

- Come up with a better name (potentially_advected_quantities) for tracer_concentration since a) it contains cloud fraction and TKE and b) it can contain non-advected quantities. 
- Improve flag names because "flag_for_PBL" is not descriptive enough. 
- Change mixing ratios to say wrt what.
- Change volume mix ratio to units of mol mol-1.
- Change xyz_number_concentration to number_concentration_of_xyz.

2021-08-24 20:44 UTC, dudhia commented
If there is still a chance, the *classification_real unit can be changed to
something else like 'category' to comply with stricter rules for the use of
'index'.
This applies to lines 1507, 1585 and 1615 of the *.md file.

On Mon, Aug 23, 2021 at 8:09 PM ligiabernardet ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Thank you @grantfirl <https://github.com/grantfirl> for addressing
> several of the previous comments and concerns including:
>
>    - Come up with a better name (potentially_advected_quantities) for
>    tracer_concentration since a) it contains cloud fraction and TKE and b) it
>    can contain non-advected quantities.
>    - Improve flag names because "flag_for_PBL" is not descriptive enough.
>    - Change mixing ratios to say wrt what.
>    - Change volume mix ratio to units of mol mol-1.
>    - Change xyz_number_concentration to number_concentration_of_xyz.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/13#pullrequestreview-736716850>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77GXUQ345ARPUVQ3BILT6L5PBANCNFSM44IFYSVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-31 22:26 UTC, gold2718 approved these changes
Ok, let's do this!

2021-08-31 22:28 UTC, merged