Rules for creating CCPP standard names
ESCOMP/CCPPStandardNames pull request #14
Opened 2021-05-18 20:04 UTC by ligiabernardet

Initial import of a file containing information about the rules for CCPP standard names. The information includes references to the CF convention, a list of qualifiers (extending the CF convention), a list of generic names (with corresponding units) that are used when creating standard names, and a list of acronyms, abbreviations, and aliases.

2021-05-20 21:59 UTC, climbfuji commented on StandardNamesRules.rst
> +| **due_to_shoc**
Is this too specific?

2021-05-20 21:59 UTC, climbfuji commented on StandardNamesRules.rst
> +| TKE                 | turbulent kinetic energy                                |
Aren't standard names case insensitive?

2021-05-20 22:27 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   [*surface*] [*component*] standard_name [``at`` *surface*] [``in`` *medium*]
This is part of the [CF convection](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html#surface). The explanation they provide is : "In the standard name, some surfaces are named by single words which are placed at the start: toa (top of atmosphere), tropopause, surface. Other surfaces are named by multi-word phrases put after at: at_adiabatic_condensation_level, at_cloud_top, at_convective_cloud_top, at_cloud_base, at_convective_cloud_base, at_freezing_level, at_ground_level, at_maximum_wind_speed_level, at_sea_floor, at_sea_ice_base, at_sea_level, at_top_of_atmosphere_boundary_layer, at_top_of_atmosphere_model, at_top_of_dry_convection."

If desirable, I can add more details to the CCPP rules, so it is clearer when to put the surface at the beginning of the name versus at the end.

2021-05-20 22:28 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| TKE                 | turbulent kinetic energy                                |
Yes, so I think I can remove the upper case aliases.

2021-05-20 22:41 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **due_to_shoc**
All these names are already in use in https://github.com/ESCOMP/CCPPStandardNames/pull/13. In other words, they are needed in the current CCPP. Therefore, I think we need them.

2021-05-20 22:54 UTC, climbfuji commented on StandardNamesRules.rst
> +   [*surface*] [*component*] standard_name [``at`` *surface*] [``in`` *medium*]
Thanks for the explanation, I'll leave it up to you whether to provide further details in the CCPP rules or not.

2021-05-21 19:48 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| TKE                 | turbulent kinetic energy                                |
Fixed

2021-06-24 23:13 UTC, gold2718 commented on StandardNamesRules.rst
> +   use at_interface.
I think this rule may be in conflict with CF which sometimes seems to make different assumptions (not always self-consistent). It would be great to have a "get out of rule free" card that says to explicitly use `layer` to resolve ambiguous situations.

2021-07-14 21:41 UTC, cacraigucar requested changes

2021-07-20 20:12 UTC, climbfuji approved these changes

2021-07-20 21:48 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   use flag_for_X. If it is any other data type, use control_for_X.All flags
This is a good suggestion but I do not know how to write a RST file that will display in color. We were using _italics_ to represent placeholders and **bold** to represent qualifiers that do not exist in the CF convention. However, RST does not support nested special characters such as **_bold italic_**. Do you have any suggestion?

2021-07-20 21:48 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| IR                  | infared                                                 |
Agreed, I will do that.

2021-07-20 21:58 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **at_surface_adjacent_layer OR at_bottom_layer OR at_lowest_model_layer**
These options are historic and I will remove them. The only remaining qualifier will be at_surface_adjacent_layer. The other qualifiers (at_bottom_layer and at_lowest_model_layer) are not used in the dictionary of Standard Names.

2021-07-20 22:00 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **of_new_state OR updated_by_physics**
I will remove updated_by_physics since it is not used in the dictionary of Standard Names The only remaining qualifier will be of_new_state.

2021-07-20 22:03 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **tunable_parameters[s]_for_X**
One "s" should be removed (I will change this). The qualifier is tunable_parameter[s].
Tunable parameters are coefficients within parameterizations. They can be "tuned" to achieve the desired results in a simulation. They are considered tunable because they do not have a correct known value (a range of values may be acceptable).

2021-07-20 23:13 UTC, ligiabernardet commented on StandardNamesRules.rst
> +^^^^^^^^^^^^^^^^^^^^^
I will separate them

2021-07-20 23:20 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   use at_interface.
The CF is not geared toward numerical modeling, so it does not have subtleties such as layers vs interfaces. So I think we have discretion here to make our own rule. I am not seeing any ambiguous situations at the moment, that is: 1) default is layer, 2) if not layer, a qualifier must be used to denote  where the variable is defined. 
Do you have any suggestion?

2021-07-22 02:37 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **real**
Yes, it is referring to a computer _real_ vs _integer_. I will look at those variables and get back to you.

2021-07-22 03:16 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   [``due_to`` *process*] [``assuming`` *condition*]
"Transformation" qualifiers always appear the beginning of the standard name, so I will make that clear in the positional hierarchy. The "Computational" qualifiers are more complex, in that sometimes they appear at the beginning, such as _flag_for_, and sometimes at the end, such as _for microphysics_. At this time I propose that we do not add computational qualifiers to the positional hierarchy, and we can revisit the topic in the future.

2021-07-22 16:41 UTC, cacraigucar commented on StandardNamesRules.rst
> +   use flag_for_X. If it is any other data type, use control_for_X.All flags
My knowledge of RST is limited. Before I made the request, I did a google search and found this:  https://stackoverflow.com/questions/4669689/how-to-use-color-in-text-with-restructured-text-rst2html-py-or-how-to-insert-h

If this works, I'd suggest using color

2021-07-22 16:43 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   use flag_for_X. If it is any other data type, use control_for_X.All flags
I  also have been googling. I don't think the suggestion you sent will work because it depends on CCS/HTML to display. 
I will have a commit soon with a proposed format to address this issue. Coming soon.

2021-07-22 23:15 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **real**
I agree that the __real_ qualifier is awkward because this information should be in the _type_ metadata, and not in the standard name. However, today we need this qualifier because the CCPP Physics has the same variable in integer and real form and the CCPP Framework does not distinguish them. So we need the distinction to be in the standard name.
After discussion within the CCPP team at DTC, here is what we suggest for the way forward. We will eliminate this undesirable rule even though we have _real standard names, and we will do follow up development to solve this problem. See https://github.com/NCAR/ccpp-physics/issues/704.

2021-07-23 03:30 UTC, ligiabernardet commented
@cacraigucar and @gold2718 I believe I have addressed your comments, pls take a look.

2021-07-23 16:00 UTC, cacraigucar requested changes

2021-07-23 16:00 UTC, cacraigucar commented on StandardNamesRules.rst
> +| **from_wave_model**
These are suffixes

2021-07-23 16:00 UTC, cacraigucar commented on StandardNamesRules.rst
> +------
There is nothing here (should it be removed)?

2021-07-23 16:00 UTC, cacraigucar commented on StandardNamesRules.rst
> +| **flag_for_reading** ``_X`` **_from_input**
These are not suffixes (since they are in the middle).  Should there be a `middle` or `infix` category for these two.  (Note I didn't know the word `infix` before I googled it).

2021-07-23 18:25 UTC, ligiabernardet commented on StandardNamesRules.rst
> +------
Underneath "Medium" it says "Suffixes" and, underneath that, there are a number of standard names. Looks ok to me as is.

2021-07-23 18:27 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **flag_for_reading** ``_X`` **_from_input**
@cacraigucar This has been addressed. Pls take a look.

2021-07-23 18:27 UTC, ligiabernardet commented on StandardNamesRules.rst
> +| **from_wave_model**
@cacraigucar This has been addressed. Pls take a look.

2021-07-23 19:45 UTC, cacraigucar approved these changes

2021-07-23 19:45 UTC, cacraigucar commented on StandardNamesRules.rst
> +------
Sorry - my reading mistake.  I thought it was a placeholder for things that weren't suffixes or prefixes.

2021-07-27 22:18 UTC, gold2718 approved these changes

2021-07-27 22:18 UTC, gold2718 commented on StandardNamesRules.rst
> +   use at_interface.
This is good (discussed at 2021-07-27 framework meeting).

2021-07-27 22:18 UTC, merged