Clarification wrt mixing ratios
ESCOMP/CCPPStandardNames pull request #16
Opened 2021-07-30 18:21 UTC by ligiabernardet

In these PR I clarified the use of (mass and volume) mixing ratios, as well as the representation of soil moisture. These clarifications are meant to address comments submitted during the review of  https://github.com/ESCOMP/CCPPStandardNames/pull/13.

2021-07-30 18:22 UTC, ligiabernardet commented
@gold2718 @climbfuji @dudhia

2021-07-30 18:51 UTC, climbfuji approved these changes
I like this! Thanks!

2021-07-30 19:11 UTC, cacraigucar commented
Adding @mattldawson as he pointed out the inconsistency initially.

2021-07-30 20:06 UTC, dudhia commented on StandardNamesRules.rst
> +   qualified as *volume_mixing_ratio*. Mass mixing ratios should contain information regarding
Volume mixing ratio sentence may not be needed as examples of this would be unlikely in microphysics schemes.

2021-07-30 20:11 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   qualified as *volume_mixing_ratio*. Mass mixing ratios should contain information regarding
Volume mixing ratio appear for chemical compositions, and are important in radiation parameterizations. We already have several standard names that start with _volume_mixing_ratio_ (of co2, n2o, ch4, etc.). So, I think this sentence is needed.

2021-07-30 20:11 UTC, dudhia commented on StandardNamesRules.rst
> +
Soil moisture should be a separate point from the microphysics paragraph above.

2021-07-30 20:16 UTC, dudhia commented
Maybe some separation of microphysics, radiation, and soil paragraphs could
be done.

On Fri, Jul 30, 2021 at 2:11 PM ligiabernardet ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In StandardNamesRules.rst
> <https://github.com/ESCOMP/CCPPStandardNames/pull/16#discussion_r680193839>
> :
>
> > @@ -56,6 +56,15 @@ CCPP Standard Name Rules
>     representing quantities at the interface between grid cells vertically,
>     use at_interface.
>
> +#. By default, *mixing_ratio* refers to mass mixing ratios. Volume mixing ratios should be
> +   qualified as *volume_mixing_ratio*. Mass mixing ratios should contain information regarding
>
> Volume mixing ratio appear for chemical compositions, and are important in
> radiation parameterizations. We already have several standard names that
> start with *volume_mixing_ratio* (of co2, n2o, ch4, etc.). So, I think
> this sentence is needed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/16#discussion_r680193839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77HD6H4ADQSX6F3ACJLT2MBO7ANCNFSM5BI75A4Q>
> .
>

2021-07-30 22:36 UTC, gold2718 requested changes
I have a couple of questions and one suggested change.

2021-07-30 22:36 UTC, gold2718 commented on StandardNamesRules.rst
> +   qualified as *volume_mixing_ratio*. Mass mixing ratios should contain information regarding
I would still like the term, "mass mixing ratio", to appear in the field's long_name property. Could this be added?

Also, as long as we are at it, should we add a rule for number concentration? The usage in #13 sometimes has the term last (e.g., `prescribed_cloud_droplet_number_concentration`) and sometimes it is first (e.g., `mass_number_concentration_of_aerosol_from_gocart_climatology`). CF seems to always have it first (although it does not have any terms called `mass_number_concentration`).

2021-07-30 22:45 UTC, ligiabernardet commented on StandardNamesRules.rst
> +   qualified as *volume_mixing_ratio*. Mass mixing ratios should contain information regarding
While these rules are for standard names, we can add a recommendation for using the word "mass" in the long name.

2021-07-30 22:45 UTC, ligiabernardet commented on StandardNamesRules.rst
> +
OK, we can put the soil aspect in a different bullet

2021-07-30 22:52 UTC, ligiabernardet commented on StandardNamesRules.rst
> ++-------------------------------------------+-----------------+
I asked Mike Iacono of AER, is involved with the RRTMG development, and he recommended mol mol-1. These units also appear in various sites when I do a web search, such as https://www.e-education.psu.edu/meteo300/node/534 or https://www.sciencedirect.com/topics/earth-and-planetary-sciences/mixing-ratio. I wouldn't say these sites are authoritative, but that seems to be how scientists use this quantity.

2021-07-30 23:00 UTC, ligiabernardet commented
Regarding @gold2718 's comment about number concentration, we can indeed clarify this in the rules. We likely want _number_concentration_of_X_, to match CF conventions. For number concentration, per unit of volume (m-3) is the default and if the quantity is per unit of mass (kg -1), a qualifier must be used: _mass_number_concentration_.

2021-07-30 23:36 UTC, gold2718 commented on StandardNamesRules.rst
> ++-------------------------------------------+-----------------+
@mattldawson, @AndrewJConley, are these units okay with you? Is `volume_mixing_ratio` better than `molar_mixing_ratio`?

I guess that the volume mixing ratio has the same value as the molar mixing ratio as long as the ideal gas equation holds.

2021-07-30 23:51 UTC, mattldawson commented on StandardNamesRules.rst
> ++-------------------------------------------+-----------------+
In my experience, `volume_mixing_ratio` with units of `mol mol-1` is most common (with the assumption of an ideal gas), but I will ask the chemists about this.

2021-08-01 19:45 UTC, mattldawson commented on StandardNamesRules.rst
> ++-------------------------------------------+-----------------+
Louisa agrees and votes for `volume_mixing_ratio` in units of `mol mol-1`

2021-08-02 23:03 UTC, ligiabernardet commented
All comments have been addressed in the last update. Please take a look.

2021-08-03 03:09 UTC, gold2718 commented on StandardNamesRules.rst
> +   qualified as *volume_mixing_ratio*. Mass mixing ratios should contain information regarding
I am okay with this change, @dudhia, please "Resolve" this conversation if you agree.

2021-08-03 03:10 UTC, gold2718 approved these changes
Looks good now, thanks!

2021-08-03 15:10 UTC, dudhia commented on StandardNamesRules.rst
> +
Looks fine now.

2021-08-03 22:55 UTC, merged