Add JEDI UFO CF-compliant names
ESCOMP/CCPPStandardNames pull request #28
Opened 2023-01-06 21:30 UTC by svahl991

The [JCSDA JEDI software project](https://www.jcsda.org/jcsda-project-jedi) has decided to adopt the CCCP naming standard to use for model variables in its generic code. This PR adds some variable names to CCCP that are already CF-standards and are in use in JEDI.

This is my first attempt at a PR for this repository, so apologies if I haven't done it quite right. I'm happy to modify.

2023-01-08 10:55 UTC, gold2718 reviewed
I am only commenting on the xml file since the md file is generated.
These additions look like they are following the rules, however, in one case, I'm not sure what the more specific CCPP version would be.
One solution is to add the full and specific definition as a `long_name` attribute.
On the other hand, if the CF name is _not_ specific, I think we should switch to using the CCPP standard.
Thoughts?

2023-01-08 10:55 UTC, gold2718 commented on standard_names.xml
> +    </standard_name>
Should (does) this specify `dry`, `moist`, or `wet` air?
I realize that these are CF standard names, however, I do not understand what the specific meaning of `_in_air` means in CF. Can anyone enlighten me here?

2023-01-08 10:55 UTC, gold2718 commented on standard_names.xml
> +    <standard_name name="humidity_mixing_ratio">
This standard name is not following the CCPP rules which would be.
```
    <standard_name name="water_vapor_mixing_ratio_wrt_dry_air">
```
On the other hand, `humidity_mixing_ratio` _is_ a CF standard name. So by rule 1, this is the correct name. Fun!

2023-01-10 18:50 UTC, cacraigucar commented on standard_names.xml
> +    </standard_name>
NOAA and NCAR had extensive discussions about how to label winds in a generic way a number of years ago.  With various grids where the wind components don't follow a east/west lines, we had decided that a generic x/y coordinate label was preferable.  @grantfirl - What are your thoughts?  @svahl991 - Would you folks be willing to adopt this more generic name?

2023-01-10 18:50 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="height">
We already have height_above_main_sea_level Would this variable be identical?

2023-01-10 18:50 UTC, cacraigucar commented on standard_names.xml
> +    </standard_name>
I was surprised that we didn't already have `relative_humidity`, but I don't see something which I think would be it currently in our list.  @grantfirl - do you agree?

2023-01-10 21:03 UTC, svahl991 commented on standard_names.xml
> +    </standard_name>
The question of whether JEDI is willing to adopt x/y instead of east/north for winds is probably above my pay grade. I can imagine a situation where a particular JEDI algorithm would work with east/north winds but not with all more generic x/y winds, and so JEDI would want to be able to distinguish between the two, but I don't know if that is a real situation or not. I can ask others with more expertise about this.

I will also note that such a change does come with a cost to more than just the core JEDI codebase. JEDI is used by many different atmospheric models, not just NOAA and NCAR models, all of which will need to change or translate existing east/north names in their code in order to communicate with JEDI if JEDI does not accept east/north names. There are cases where JEDI is using non-CCPP-compliant variable names where we already know we will need to incur this difficulty, but I was hoping it could be avoided for names that are already CF-compliant. I thought that a CF-compliant name was also a CCPP-compliant name, based on Rule number 1, but based on the discussions I'm seeing in this PR, it appears that might not be true. Perhaps rule number 1 could be clarified?

2023-01-10 21:45 UTC, climbfuji commented on standard_names.xml
> +    </standard_name>
I have the same concern that @svahl991 has w.r.t. that some algorithm may be relying on eastward and northward, and not generic x/y directions. I know that MPAS for example computes east/north winds from its generic wind directions (which are orthogonal to the cell faces) to pass them to the physics, but is JEDI using those east/north winds or the "native" wind directions from the MPAS mesh?

If JEDI does require true east and north, and not generic x and y, then that's what it should be using as standard names. If it doesn't need true east and north, but arbitrary orthogonal x and y, then it should be using x and y. My 2c.

2023-01-10 22:34 UTC, cacraigucar commented on standard_names.xml
> +    </standard_name>
I second @climbfuji's take on east/west versus x/y.  If a package needs east/west then it should use those specific names.  But if it happens to be east/west but would work for any orthogonal directions, for flexibility sake it should use the x/y names.

Also, the standard names are only in the CCPP metadata.  If internally code wants to continue using the names with east/west, they can do that and link them to the x/y CCPP names in the metadata.   This means that I don't think code rewrites need to be done to change internal variable names.

2023-01-10 22:46 UTC, grantfirl commented on standard_names.xml
> +    </standard_name>
I agree. If the variables truly represent east/west, then those names should be kept. CF doesn't specify, but I'm assuming that east/west is in reference to geographic direction as opposed to magnetic or some other definition. Perhaps zonal and meridional would work better to avoid any confusion, but those aren't actually CF names. Weird.

2023-01-10 22:47 UTC, grantfirl commented on standard_names.xml
> +    <standard_name name="humidity_mixing_ratio">
Ya, this is exhibit A why we've been extending CF.

2023-01-10 22:51 UTC, grantfirl commented on standard_names.xml
> +    </standard_name>
Yes. UFS uses relative_humidity, but it is in the interstitial DDT which we yet to parse for standard name rules and added to this repo. It should absolutely be added.

2023-01-11 20:35 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="humidity_mixing_ratio">
After discussion with @nusbaume here on the NCAR side, we agree with @gold2718 that the standard name should be `water_vapor_mixing_ratio_wrt_dry_air` and not the `humidity_mixing_ratio` which is originally proposed.

2023-01-19 19:29 UTC, svahl991 commented on standard_names.xml
> +    </standard_name>
We discussed this more with a group here at the JCSDA and we feel we do need to keep the east/west names as the x/y names are too general for all our needs.

2023-01-19 20:08 UTC, climbfuji commented on standard_names.xml
> +    </standard_name>
To add a bit more information, there is an identity operator in JEDI for obs and those obs report geographical directions, therefore those specific names are needed.

2023-01-19 23:22 UTC, BenjaminTJohnson commented on standard_names.xml
> +    <standard_name name="humidity_mixing_ratio">
Shouldn't these also specify whether it's a "volume mixing ratio" or a "mass mixing ratio"?

2023-01-19 23:27 UTC, svahl991 commented on standard_names.xml
> +    <standard_name name="humidity_mixing_ratio">
> Shouldn't these also specify whether it's a "volume mixing ratio" or a "mass mixing ratio"?

By rule number 5 here: https://github.com/ESCOMP/CCPPStandardNames/blob/main/StandardNamesRules.rst, I think the default is to refer to mass mixing ratio unless otherwise specified.

2023-01-20 02:35 UTC, climbfuji commented on standard_names.xml
> +    <standard_name name="humidity_mixing_ratio">
Correct

2023-01-24 16:01 UTC, gthompsnJCSDA commented on standard_names.xml
> +    <standard_name name="height">
If there is already a CCPP height variable with the name `height_above_mean_sea_level` then we should not confuse people with an added variable named only `height`.  Notice the spelling of `main` in the comment from @cacraigucar appears to be a mistake and should be as I typed it with `mean_sea_level` in the name.

2023-01-24 16:44 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="height">
Yup - a typo - I've corrected

2023-01-24 17:26 UTC, svahl991 commented on standard_names.xml
> +    <standard_name name="height">
OK. I will remove `height` from this PR.

2023-01-26 17:11 UTC, cacraigucar commented on standard_names.xml
> +    </standard_name>
It appears that this use of east/west is appropropriate, so I will resolved this conversation

2023-01-26 17:12 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="height">
Once the removal of `height` is pushed back to this PR, I will resolve this conversation.  This appears to be the last outstanding comment I have before I can give my approval.

2023-01-27 18:15 UTC, cacraigucar commented on standard_names.xml
> +    </standard_name>
@fvitt and/or @mattldawson - From a chemistry standpoint do either of you have any insights on how folks in your community explicitily describe `mole_fractions`?

2023-01-27 20:15 UTC, svahl991 commented on standard_names.xml
> +    </standard_name>
Thanks to @huishao-r, who found this description for me:
https://vocab.nerc.ac.uk/collection/P07/current/CFV7N47/
Is this helpful? I don't know if it explicitly answers the dry/moist/wet question. My guess is that it is assumed to just be in the atmosphere. Does dry/moist/wet need to be specified in all contexts?

2023-01-27 20:35 UTC, BenjaminTJohnson commented on standard_names.xml
> +    </standard_name>
I'm not sure if this is helpful or not, but we never use that unit inside of CRTM.

2023-01-27 22:07 UTC, gthompsnJCSDA commented on standard_names.xml
> +    </standard_name>
I will throw in my 2 cents here.  We live in a moist world.  The air around us is filled with molecules of water vapor alongside CO2, O2, N2, O3, etc.  For those models that use a "dry_air" reference point, then I say make those models add "dry_air" to their wording otherwise "in_air" can be interpreted as being with reference to moisture included since that is the physical world we live in.  The word "wet" being used is so highly confusing.

Molecules of various constituents simply coexist.  We could have moles of water vapor per mole of air, moles of CO per mole of air, moles of CO2 per mole of air, etc.  Taking one type of molecule type out (i.e., water vapor) makes zero sense because it's like defining another constituent after taking away the N2 molecules or something.  There's no end to the possibilities.  So the definition - **again in my opinion** - should be consistent with the physical world of air is a mixture of gases so we shouldn't define a variable with regard to dry (non-H2o) air if we are not eliminating the other constituents.

I think I'm showing my frustration towards model concepts that don't relate well to real world. If a modeler cannot output the data into variables of a physical world by simply including H2O molecules in air, then why not?  They don't go around excluding the other constituents so poor water vapor is always picked on :)

2023-01-27 22:24 UTC, dudhia commented on standard_names.xml
> +    </standard_name>
From a physics perspective this would be relative to total air, the way ppm by volume is, and it would be directly proportional to ppmv.

2023-01-27 23:02 UTC, svahl991 commented on standard_names.xml
> +    </standard_name>
Thanks to everyone for chiming in on this discussion today! After these clarifications, is there still a question we're trying to answer here? If so, can it be stated? Of course the question I'm most interested in is: will this PR be approved with these two `mole_fraction_*` variables named as they are?

2023-01-27 23:05 UTC, dudhia commented on standard_names.xml
> +    </standard_name>
Based on my comment, this name is sufficient.

2023-01-27 23:34 UTC, cacraigucar requested changes

2023-01-27 23:34 UTC, cacraigucar commented on standard_names.xml
> +    <standard_name name="water_vapor_mixing_ratio_wrt_dry_air"
Oops - you removed the `>` at the end of this variable, along with the next two as well.

2023-01-27 23:48 UTC, svahl991 commented on standard_names.xml
> +    <standard_name name="water_vapor_mixing_ratio_wrt_dry_air"
Yes, I did that intentionally because the `long_name` on the next line is part of the same tag. I think this is the correct syntax.

When I first made the PR, I manually edited the `Metadata-standard-names.md` file, not realizing it should be generated with the Python script, which is why I didn't notice the XML formatting error in this file. @climbfuji is going to generate the `.md` file for me this time, since he has easier access to a python environment where the script will run. So this PR is currently not ready to go since the `.md` file isn't updated yet. He may also find other XML bugs when he runs the script. So we need a little more time.

2023-01-28 03:48 UTC, climbfuji commented on standard_names.xml
> +    <standard_name name="water_vapor_mixing_ratio_wrt_dry_air"
Should be done now (c1b481d)

2023-01-28 20:17 UTC, gold2718 commented on standard_names.xml
> +    </standard_name>
> Does dry/moist/wet need to be specified in all contexts?

While I sympathize with the arguments put forward by @gthompsnJCSDA, physics schemes need to know what physical quantity it is dealing with and a principle of the CCPP has been to provide that clarity.
I am fine with `mole_fraction_*` meaning with respect to total air (as opposed to 'dry air' or 'moist air'), however, if we decide this, can we please add this as a rule in StandardNamesRules.rst? That way, if anyone comes in with moles of X per moles of moist / dry air, they will have to use standard names that reflect this. I would like that addition to be part of this PR.

2023-01-30 16:56 UTC, svahl991 commented
Apologies if I accidentally removed @ligiabernardet as a reviewer on this PR. I'm not sure how that happened. I don't appear to have the ability to re-add.

2023-01-30 16:58 UTC, climbfuji commented
I added her back in. I'll review later today.

2023-01-30 19:14 UTC, gold2718 approved these changes
I think this looks great, thanks for all the work.

2023-01-30 20:12 UTC, climbfuji commented on StandardNamesRules.rst
> +#. By default, *mole_fraction_of_X_in_Y* refers to the total amount of *Y*. So, for example,
I am sorry that I need to ask one more time. It reads like total amount of Y in the case of air means total air mass, i.e  w.r.t. dry air + water vapor + all hydrometeors, as opposed to w.r.t. dry air + water vapor only. I just want to make sure that this is the intent.

2023-01-30 20:32 UTC, gthompsnJCSDA commented on StandardNamesRules.rst
> +#. By default, *mole_fraction_of_X_in_Y* refers to the total amount of *Y*. So, for example,
I do not believe the solid particles should be taken into account in this circumstance.  They would seem quite unusual.

2023-01-30 20:41 UTC, climbfuji commented on StandardNamesRules.rst
> +#. By default, *mole_fraction_of_X_in_Y* refers to the total amount of *Y*. So, for example,
> I do not believe the solid particles should be taken into account in this circumstance. They would seem quite unusual.

In this case, the rule should state that? i.e. something like "if Y is air, then the default is "wrt_moist_air" as described in rule 5?

2023-01-30 20:55 UTC, BenjaminTJohnson commented on StandardNamesRules.rst
> +#. By default, *mole_fraction_of_X_in_Y* refers to the total amount of *Y*. So, for example,
I don't know what the general consensus is, but generally mixing ratios are most useful / interesting when dealing with moist air, with the noted exception of water vapor mixing ratio, which is universally applied to dry air. 

Water vapor mixing ratio with respect to moist air is defined as "specific humidity", and they differ by as much as a few percent in the Earth's atmosphere.

2023-01-30 20:59 UTC, BenjaminTJohnson approved these changes
Looks like some long names are missing, or inconsistent in scope / style with respect to other long names, but I suppose this is something that will be iteratively added.

2023-01-30 21:02 UTC, svahl991 commented on StandardNamesRules.rst
> +#. By default, *mole_fraction_of_X_in_Y* refers to the total amount of *Y*. So, for example,
I have just pushed an update to the wording of the rule to be more clear. See [af15329](https://github.com/ESCOMP/CCPPStandardNames/pull/28/commits/af1532942e96ac01f0df5a416e68cabb38fd39ef).

2023-01-30 21:02 UTC, dudhia commented
The distinction is needed because some models refer all species to dry air.

On Mon, Jan 30, 2023 at 1:55 PM Benjamin Johnson ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In StandardNamesRules.rst
> <https://github.com/ESCOMP/CCPPStandardNames/pull/28#discussion_r1091141641>
> :
>
> > @@ -68,6 +68,10 @@ CCPP Standard Name Rules
>
>  #. Volume mixing ratios should be qualified as *volume_mixing_ratio*.
>
> +#. By default, *mole_fraction_of_X_in_Y* refers to the total amount of *Y*. So, for example,
>
> I don't know what the general consensus is, but generally mixing ratios
> are most useful / interesting when dealing with moist air, with the noted
> exception of water vapor mixing ratio, which is universally applied to dry
> air.
>
> Water vapor mixing ratio with respect to moist air is defined as "specific
> humidity", and they differ by as much as a few percent in the Earth's
> atmosphere.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESCOMP/CCPPStandardNames/pull/28#discussion_r1091141641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIZ77E4LWFWO6AG6OD2TYTWVATDPANCNFSM6AAAAAATTPIR44>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-01-30 21:13 UTC, climbfuji approved these changes

2023-01-30 22:20 UTC, climbfuji commented
I re-requested reviews from reviewers who had comments earlier.

2023-01-31 18:20 UTC, cacraigucar approved these changes

2023-02-01 20:26 UTC, climbfuji commented
We have four approvals, therefore I am going to merge this and not let it drag on for longer.

2023-02-01 20:26 UTC, merged