Add GitHub Actions CI for pull requests
ESCOMP/CCPPStandardNames pull request #34
Opened 2023-04-27 14:55 UTC by jfrost-mo

Fixes #33

Also has a second actions job to check that the markdown rendering of the standard names is up to date. It would be fairly easy to extend this to add a commit to the PR updating it if it isn't, but I haven't added that here as it wasn't really the focus.

2023-04-27 17:23 UTC, nusbaume requested changes
Thanks so much for opening this PR!  I didn't even realize the Met Office was interested in this project, but we'll happily take any help we can get.

Anyways, I tried testing the Actions workflow and found that one step related to xmllint was missing for each job.  However, once those changes are made and the merge conflict is resolved I think this PR will be good to go, at least on my end (i.e. the workflow tests all behaved as expected in my testing environment).  Of course If you need any assistance with the requested changes just let me know.

2023-04-27 17:23 UTC, nusbaume commented on .github/workflows/pull_request_ci.yml
> +
Sadly `xmllint` doesn't come with the standard runner environment so we'll need to add it here:

```suggestion
 # Install xmllint so tests pass:
      - name: Install xmllint
        run: |
            sudo apt-get update
            sudo apt-get install libxml2-utils
```

2023-04-27 17:23 UTC, nusbaume commented on .github/workflows/pull_request_ci.yml
> +
We'll have to add the `xmllint` install step here as well:

```suggestion
 # Install xmllint so tests pass:
      - name: Install xmllint
        run: |
            sudo apt-get update
            sudo apt-get install libxml2-utils
```

2023-04-28 07:48 UTC, jfrost-mo commented on .github/workflows/pull_request_ci.yml
> +
xmllint was installed on my local environment already, so I forgot about installing it. Thanks.

2023-04-28 07:54 UTC, jfrost-mo commented
I've added xmllint installation to the workflow, and rebased onto main to fix the merge conflicts.

2023-04-28 15:26 UTC, nusbaume approved these changes
Looks good to me now, thanks again!

2023-05-15 20:39 UTC, mkavulich approved these changes

2023-05-15 20:44 UTC, climbfuji approved these changes
Thanks very much for adding this capability, @jfrost-mo !

2023-05-15 22:03 UTC, merged