Add new cloud standard name rule, and update cloud_area_fraction
ESCOMP/CCPPStandardNames pull request #37
Opened 2023-05-16 18:23 UTC by nusbaume

This pull request adds a new rule specifying that unless stated otherwise, the word `cloud` means all cloud phases and types.

Also, it was brought up by @grantfirl That the standard name `cloud_area_fraction` as used in the UFS doesn't include convective clouds, so the standard name was updated, along with standard names that appeared directly related, to specify that convective clouds are not included.

Finally, I am not strongly tied to the specific wording of either the new rule or the updated standard names, and so am happy to change them to whatever people prefer.

2023-06-06 18:01 UTC, cacraigucar commented on StandardNamesRules.rst
> +
Thanks for the qualifier example update

2023-06-06 18:02 UTC, cacraigucar approved these changes

2023-06-06 18:02 UTC, cacraigucar approved these changes

2023-06-07 16:39 UTC, grantfirl requested changes
I'd prefer `non_convective` be changed to either `nonconvective` or `non-convective`. I've seen it hyphenated or combined, but never separated with a space, which is what the underscore is representing. Also, I think that we're probably going to need a more general variable at some point that includes all clouds (including convective).

2023-06-13 17:30 UTC, gold2718 commented on standard_names.xml
> +        name="non-convective_cloud_area_fraction_in_atmosphere_layer"
This violates the Standard Name Rules.
Rule 2 states that standard names must follow the [CF metadata rules for constructing standard names](http://cfconventions.org/Data/cf-standard-names/docs/guidelines.html). This document states:
"Standard names consist of lower-letters, digits and underscores, and begin with a letter. Upper case is not used."
Please remove dashes in standard names.

2023-06-17 10:33 UTC, gold2718 approved these changes
Looks okay to me now.

2023-06-26 21:27 UTC, grantfirl approved these changes

2023-06-26 22:09 UTC, merged