Add new standard names from NCAR idealized physics schemes
ESCOMP/CCPPStandardNames pull request #56
Opened 2023-12-05 20:23 UTC by nusbaume

This PR adds some new CCPP standard names that are currently being used within SIMA for NCAR idealized physics schemes.  

Along with the standard names themselves, I also added a couple extra sections for some variables that I thought wouldn't fit very nicely elsewhere.  At some point I think it would be worth discussing the organization of the standard names a little more, as there are some standard names that are listed under specific GFS DDTs but which are probably more universal than that (e.g. `mpi_rank`).  However, I don't believe this potential organizational concern needs to be resolved for this particular PR.

Finally, please note that some of the links to the new sections in the generated markdown file will be broken until PR #55 has been merged.  Thanks!

2024-01-09 19:57 UTC, mkavulich requested changes

2024-01-09 19:57 UTC, mkavulich commented on Metadata-standard-names.md
> +* [system variables](#system variables)
I see that these links are currently broken, I assume that will get fixed once #55 is merged?

2024-01-09 19:57 UTC, mkavulich commented on standard_names.xml
> +    <standard_name name="heating_rate"
This variable name feels very vague, could it be made more specific?

If the standard name needs to be kept at is, it definitely needs a more specific `long_name` entry at the very least.

2024-01-09 19:57 UTC, mkavulich commented on standard_names.xml
> +                   long_name="Total change in temperature from a physics suite">
While we're changing things, could you make this addition?
```suggestion
                   long_name="Total change in air temperature from a physics suite">
```

2024-01-09 19:57 UTC, mkavulich commented on standard_names.xml
> +    <standard_name name="ccpp_constituent_properties"
Out of curiosity, can you point me to how these constituent variables are being used in SIMA? I'm curious about the specifics of the use case (for example, why there are minimum but not maximum values).

2024-01-09 20:23 UTC, grantfirl commented on Metadata-standard-names.md
> +* [system variables](#system variables)
I personally don't like the term "standard variables" because "standard" is sort of a loaded term. It can mean normal/usual as it is meant here, but also referring to some standard. We're also using standard names to denote "the key by which a specific quantity is known by physics and hosts using the CCPP", and someone might draw some link between the two. What is really in this section are variables provided by the framework, right? So, could we change the section name to be "framework-provided", perhaps with separate sections for required framework-provided and optional framework-provided?

2024-01-09 20:26 UTC, grantfirl commented on Metadata-standard-names.md
> +* `density_of_dry_air`: Density of dry air
CF conventions use "X_density" rather than "density_of_X".

2024-01-09 20:31 UTC, cacraigucar requested changes

2024-01-09 20:31 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `print_qneg_warn`: Logging setting for negative constituent mass fixer
I'm wondering if this should be `print_qneg_warning` instead?

2024-01-09 20:31 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `cloud_liquid_water_mixing_ratio_wrt_moist_air_and_condensed_water`: Ratio of the mass of liquid water to the mass of moist air and condensed water
I'm not finding this in our local spreadsheet

2024-01-09 20:31 UTC, grantfirl commented on Metadata-standard-names.md
> +* `heating_rate`: heating rate
How is this related to "tendency_of_air_temperature"? Does it refer to the heating of anything in particular?

2024-01-09 20:33 UTC, grantfirl commented on Metadata-standard-names.md
> +* `reference_pressure_in_atmosphere_layer_normalized_by_reference_pressure`: reference pressure in atmosphere layer normalized by reference pressure
This is confusing to me. I'm guessing that the term "reference" means different things both times it is used, otherwise this would just be 1. Is there a better term than "reference" for either the first or second instance?

2024-01-09 20:35 UTC, grantfirl commented on Metadata-standard-names.md
> +* `ccpp_constituent_properties`: CCPP Constituent Properties
Do we need to have "CCPP" in the standard names added here? Aren't all standard names "CCPP" standard names in this context?

2024-01-09 20:41 UTC, grantfirl commented on Metadata-standard-names.md
> +* `print_qneg_warn`: Logging setting for negative constituent mass fixer
Agreed. Also see rule 14: `For control-oriented variables, if the variable is a Fortran logical, use flag_for _X. If it is any other data type, use control_for _X. All flags should be Fortran logicals.` So, would `control_for_negative_constituent_warning` work? I realize that this is much longer than you have, though.

2024-01-09 20:43 UTC, cacraigucar commented on Metadata-standard-names.md
> +* `ccpp_constituent_properties`: CCPP Constituent Properties
I think at least this particular name should have ccpp in its name, as it will be the CCPP derived data type.   I don't have a strong feeling for the other variables listed below this one.

2024-01-09 20:47 UTC, grantfirl commented on Metadata-standard-names.md
> +* `ccpp_constituent_properties`: CCPP Constituent Properties
Maybe it's OK to keep `ccpp` in the standard name and maybe add a rule that all variables that start with `ccpp_X` are provided by the framework.

2024-01-18 15:28 UTC, nusbaume commented on Metadata-standard-names.md
> +* [system variables](#system variables)
@mkavulich - Yes!  In fact I just merged in that PR and updated this branch, so the links should be fixed now.  Of course please let me know if they still don't work properly for you.

@grantfirl - This is a good point.  I went ahead and changed these sections to be `framework-provided variables` as suggested in order to avoid the overuse of the word "standard".

2024-01-18 15:31 UTC, nusbaume commented on standard_names.xml
> +                   long_name="Total change in temperature from a physics suite">
Done!

2024-01-18 15:36 UTC, nusbaume commented on standard_names.xml
> +    <standard_name name="ccpp_constituent_properties"
Sure!  You can find an example of us using it to calculate geopotential here:  https://github.com/ESCOMP/atmospheric_physics/blob/main/utilities/geopotential_temp.F90  

with the associated metadata file here:  https://github.com/ESCOMP/atmospheric_physics/blob/main/utilities/geopotential_temp.meta).  

We also use them for our negative constituent adjuster here:  https://github.com/ESCOMP/atmospheric_physics/blob/main/utilities/qneg.F90

with the associated metadata file here:  https://github.com/ESCOMP/atmospheric_physics/blob/main/utilities/qneg.meta)

If you have any questions or concerns about these routines or the general use of these data structures just let me know!

2024-01-18 15:36 UTC, nusbaume commented on Metadata-standard-names.md
> +* `density_of_dry_air`: Density of dry air
Good catch!  Standard name changed to `dry_air_density`.

2024-01-18 15:37 UTC, nusbaume commented on Metadata-standard-names.md
> +* `print_qneg_warn`: Logging setting for negative constituent mass fixer
@cacraigucar @grantfirl Thanks for catching this!  Went ahead and changed it to `control_for_negative_constituent_warning` to best match the naming rules.

2024-01-18 15:37 UTC, nusbaume commented on Metadata-standard-names.md
> +* `cloud_liquid_water_mixing_ratio_wrt_moist_air_and_condensed_water`: Ratio of the mass of liquid water to the mass of moist air and condensed water
Thanks for checking!  The name in the spreadsheet was wrong, but has been fixed now.

2024-01-18 15:39 UTC, nusbaume commented on Metadata-standard-names.md
> +* `heating_rate`: heating rate
See the explanation I gave Mike here:  https://github.com/ESCOMP/CCPPStandardNames/pull/56#discussion_r1457612371

Happy to change the name if one of the alternative names is better (I can also update the long name if preferred).

2024-01-18 15:45 UTC, nusbaume commented on Metadata-standard-names.md
> +* `reference_pressure_in_atmosphere_layer_normalized_by_reference_pressure`: reference pressure in atmosphere layer normalized by reference pressure
Yeah, the issue is that this is basically the variable with the accepted standard name `reference_pressure_in_atmosphere_layer`, which is a 1-D array, divided by the variable with the accepted standard name `reference_pressure`, which is a scalar.

If I remember correctly there were possibly different terms for this quantity.  @PeterHjortLauritzen  @adamrher @JulioTBacmeister do any of you remember?  To help jog your memory this quantity is the same as `pref_mid_norm` in `ref_pres.F90` in CAM.

2024-01-18 15:46 UTC, nusbaume commented on Metadata-standard-names.md
> +* `ccpp_constituent_properties`: CCPP Constituent Properties
I have updated the rules to make it clear that any standard name that starts with `ccpp_` should be a framework-provided variable.

2024-01-18 22:59 UTC, nusbaume commented on Metadata-standard-names.md
> +* `reference_pressure_in_atmosphere_layer_normalized_by_reference_pressure`: reference pressure in atmosphere layer normalized by reference pressure
After chatting with folks I think everyone is ok with changing `reference_pressure` to `surface_reference_pressure`.  So this standard name would become:

`reference_pressure_in_atmosphere_layer_normalized_by_surface_reference_pressure`

Would that work for you @grantfirl ?  If so I'll go ahead and update both this standard name and the `reference_pressure` standard name.

2024-01-18 23:03 UTC, nusbaume commented
@mkavulich @grantfirl @cacraigucar I forgot to mention that I also added some changes to `meta_stdname_check.py` to ensure that the printed output maintains the same order everytime, which hopefully explains the new changes to that script.  Of course if you would like me to make a separate issue for it just let me know.  Thanks!

2024-01-19 05:36 UTC, mkavulich commented on standard_names.xml
> +    <standard_name name="heating_rate"
I think `tendency_of_dry_air_enthalpy_at_constant_pressure` is much better, despite how much the term "enthalpy" gives me undergrad thermodynamics flashbacks. We could also keep the standard name as "`heating_rate_of_dry_air`" and include the enthalpy descriptor as the long name.

It occurs to me that there is really no guidance at all for "long names" in the standards. Maybe a discussion topic for a future meeting?

2024-01-22 23:41 UTC, cacraigucar approved these changes

2024-01-24 14:57 UTC, grantfirl commented on standard_names.xml
> +    <standard_name name="heating_rate"
Yes, @nusbaume, the new standard name is much clearer. Thanks. @mkavulich Long names have always just functioned as documentation basically. The framework ignores them. They can be context-dependent, i.e. have differences between metadata files, if it makes sense to do so.

2024-01-24 14:58 UTC, grantfirl commented on Metadata-standard-names.md
> +* `reference_pressure_in_atmosphere_layer_normalized_by_reference_pressure`: reference pressure in atmosphere layer normalized by reference pressure
Yes, that is clearer. Thanks.

2024-01-24 15:01 UTC, grantfirl commented
@nusbaume I'll approve once you commit those couple of changes that we discussed. Please tag me with @ when you're done so that I get an email (that I hopefully see!).

2024-01-25 15:50 UTC, nusbaume commented on standard_names.xml
> +    <standard_name name="heating_rate"
@mkavulich @grantfirl The standard name has now been changed.  Thanks!

2024-01-25 15:50 UTC, nusbaume commented on Metadata-standard-names.md
> +* `reference_pressure_in_atmosphere_layer_normalized_by_reference_pressure`: reference pressure in atmosphere layer normalized by reference pressure
@grantfirl Great!  The standard names have now been changed.

2024-02-26 21:57 UTC, grantfirl approved these changes

2024-02-27 03:38 UTC, merged