Add water variables
ESCOMP/CCPPStandardNames pull request #69
Opened 2024-05-10 12:11 UTC by MayeulDestouches

This PR extends a few variables related to atmospheric water:

- It extends the 3D mass contents to include a rain, snow, graupel and hail versions. 
- It extends the water mixing ratios of water vapor, cloud ice, cloud liquid water and rain by adding variants with the `_at_top_interfaces` vertical stagger. I only updated the mixing ratios wrt dry air and the mixing ratios wrt moist air and condensed water, as I don't need the mixing ratios wrt moist air alone.

It also adds a few water-related variables:
- Mixing ratios of total water.
- `water_vapor_mixing_ratio_wrt_moist_air_and_condensed_water_assuming_saturation` for saturated specific humidity.
- `derivative_of_ln_water_vapor_partial_pressure_assuming_saturation_wrt_air_temperature` for the log derivative of saturation vapor pressure wrt temperature.
- The `_at_top_interaces` variants of the latter two variables.

2024-05-10 12:12 UTC, MayeulDestouches commented
Tagging @danholdaway for information.

2024-05-14 18:16 UTC, mkavulich approved these changes
Looks good to me. We noticed in our weekly meeting that this PR was not assigned the correct codeowners for review due to an incorrect setting, so I have added them manually.

2024-05-16 07:45 UTC, MayeulDestouches commented on standard_names.xml
> +    </standard_name>
Graupel and hail are different things, so you can definitely use both hail "mass content" and graupel "mass content", although I kwow schemes  which assume that all graupel and hail can be considered as graupel, for simplification.

I didn't know about the `do_hail_instead_of_graupel` and `do_graupel_instead_of_hail` flags. My guess is that these flags are used in the some part of GFS microphysics scheme do activate similar simplifications. 
Maybe @grantfirl (who added these flag names) or @gthompsnJCSDA can give some insight on this.

2024-05-16 10:43 UTC, gold2718 commented on standard_names.xml
> +    </standard_name>
> Graupel and hail are different things

Well for sure I'd rather get hit on the head with graupel :)

2024-05-20 18:51 UTC, nusbaume requested changes
Looks good to me, but did have one change request and a question.

2024-05-20 18:51 UTC, nusbaume commented on standard_names.xml
> +                   long_name="Ratio of the mass of ice to the mass of moist air and condensed water">
I think (?) this long name should be changed to the following:

```suggestion
                   long_name="Ratio of the mass of ice to the mass of moist air and condensed water at all interfaces excluding surface">
```

2024-05-20 18:51 UTC, nusbaume commented on standard_names.xml
> +    <standard_name name="total_water_mixing_ratio_wrt_moist_air_and_condensed_water"
Should we add a new rule to `StandardNamesRules.rst` stating that the phrase `total_water` includes all types of water in all phases?  I realize that it is somewhat obvious, but I would rather be overly-pedantic then risk potential confusion/argument later.

2024-05-21 09:47 UTC, MayeulDestouches commented on standard_names.xml
> +                   long_name="Ratio of the mass of ice to the mass of moist air and condensed water">
Thanks for spotting this @nusbaume, this is fixed now.

2024-05-21 09:49 UTC, MayeulDestouches commented on standard_names.xml
> +    <standard_name name="total_water_mixing_ratio_wrt_moist_air_and_condensed_water"
I have added a rule to clarify what `total_water` is.

@mkavulich, this ratio is 
```
       (mass water vapor) + (mass liquid water) + (mass water ice)
----------------------------------------------------------------------------
(mass water vapor) + (mass liquid water) + (mass water ice) + (mass dry air)
```

2024-05-21 14:13 UTC, nusbaume approved these changes
Thanks for the changes @MayeulDestouches!  This PR looks ready to me now.

2024-05-21 14:29 UTC, climbfuji approved these changes
Thanks for these updates @MayeulDestouches

2024-05-21 17:42 UTC, cacraigucar approved these changes

2024-05-28 13:42 UTC, MayeulDestouches commented
Is anything missing for this PR to be merged?

2024-06-01 04:01 UTC, nusbaume commented
Sorry for the slow response!  It looks like we still need an approval from @ss421 before we can merge.

2024-06-01 21:29 UTC, ss421 approved these changes
Thankyou.

2024-06-02 18:44 UTC, merged