Add four wind CF variables
ESCOMP/CCPPStandardNames pull request #73
Opened 2024-09-13 20:10 UTC by svahl991

This adds four variables related to wind fluid dynamics. The names are already CF names that have not yet been added to the CCPP standard.

2024-09-13 20:12 UTC, svahl991 commented
Tagging @ncrossette

2024-09-16 02:22 UTC, climbfuji approved these changes

2024-09-17 16:40 UTC, gold2718 requested changes
I'm confused about one of the names.

2024-09-17 16:40 UTC, gold2718 commented on standard_names.xml
> +    <standard_name name="horizontal_divergence_of_wind"
Isn't the CF name `divergence_of_wind` because CF considers "wind" to be the horizontal component?

2024-09-17 17:28 UTC, svahl991 commented on standard_names.xml
> +    <standard_name name="horizontal_divergence_of_wind"
The note attached to `divergence of wind` (visible if you click on the name) in the [CF website](https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html) says:

> "[horizontal_]divergence_of_X" means [horizontal] divergence of a vector X; if X does not have a vertical component then "horizontal" should be omitted. Wind is defined as a two-dimensional (horizontal) air velocity vector, with no vertical component. (Vertical motion in the atmosphere has the standard name upward_air_velocity.)

So now that I read that note more carefully, I see you are correct. Thanks for catching this. I think I misread the note originally. I will make this change.

Tagging @MarekWlasak to make sure he is OK with this change, since he suggested the name with `horizontal_` to me originally.

2024-09-17 19:32 UTC, svahl991 commented on standard_names.xml
> +    <standard_name name="horizontal_divergence_of_wind"
PR has now been updated to remove `horizontal_` from `divergence_of_wind`.

2024-09-17 19:53 UTC, gold2718 approved these changes
Looks good now, thanks!

2024-09-17 19:53 UTC, gold2718 commented on standard_names.xml
> +                   long_name="The divergence of the vector wind field">
One option is to add horizontal in the long name.

2024-09-18 17:08 UTC, svahl991 commented on standard_names.xml
> +    <standard_name name="horizontal_divergence_of_wind"
> .... but wind does have 3 components (u,v w), so we do need the `horizontal_` bit otherwise we are talking about the 3 dimensional divergence!

I believe what the CF standard is saying in their comment is that wind is defined to be a 2-D variable, with the vertical component broken out as a separate variable (`upward_air_velocity`), and that's why the `horizontal_` prefix is not required in the `divergence_of_wind` name.

2024-09-18 17:23 UTC, svahl991 commented on standard_names.xml
> +                   long_name="The divergence of the vector wind field">
I have now updated the long name to make it more descriptive and to specifically mention that wind is 2-D.

2024-09-19 08:32 UTC, MarekWlasak commented on standard_names.xml
> +    <standard_name name="horizontal_divergence_of_wind"
Ok. Just checked the CF standard.  The `wind` tag is indeed defined as implicitly `horizontal`, so no need for the prefix.  I am bit surprised by this though, as there is no tag for a 3D wind!

2024-09-19 08:34 UTC, MarekWlasak approved these changes

2024-09-19 11:34 UTC, merged

2024-10-09 11:21 UTC, MarekWlasak commented
My concerns and suggestions are in https://github.com/ESCOMP/CCPPStandardNames/issues/77