Add/modify variable names related to surface height/pressure
ESCOMP/CCPPStandardNames pull request #76
Opened 2024-09-24 15:07 UTC by svahl991

This adds two names relating to height at surface, and modifies `surface_air_pressure` for the naming rule change coming in #72.

(I realize that there is more renaming of existing variables to be done as a product of #72, so I can remove `surface_air_pressure` from this PR if people feel it is better to do that rename in a group with the others. It's just that this name is of particular interest to the fast-approaching JEDI renaming code sprint, so I wanted to be sure to get it in.)

2024-09-24 16:28 UTC, gold2718 approved these changes
Looks good!

2024-09-24 16:29 UTC, climbfuji approved these changes

2024-09-24 17:18 UTC, nusbaume requested changes
Looks good!  Just had one request.

2024-09-24 17:18 UTC, nusbaume commented on standard_names.xml
> +                   long_name="geopotential height at local surface">
We might need to specify what this field is in relation to, for example:

```suggestion
                   long_name="geopotential height at local surface w.r.t. sea level">
```

2024-09-24 17:25 UTC, svahl991 commented on standard_names.xml
> +                   long_name="geopotential height at local surface">
I've now added `w.r.t. sea level`. Also capitalized `Geopotential` in `long_name` since that seems to be standard.

2024-09-24 17:42 UTC, cacraigucar approved these changes

2024-09-24 23:20 UTC, ss421 approved these changes

2024-09-30 12:39 UTC, climbfuji commented
@mkavulich @dustinswales this is ready for your final review and merging - thanks!

2024-10-01 15:20 UTC, dustinswales approved these changes
I see no issue with these changes/additions.

2024-10-01 17:11 UTC, merged