add emissions names
ESCOMP/CCPPStandardNames pull request #86
Opened 2024-12-11 21:52 UTC by jeromebarre

This adds emissions names to the CCPP standard names

2024-12-12 23:49 UTC, mkavulich requested changes
@jeromebarre I have some suggested changes. We don't have any "emission" variables in the standard names yet but I think this will be more in line with how other variables are handled.

I also had a question as to the lumping of residential and commercial sources: is there a potential use case for emissions of residential only or commercial only? They don't need to necessarily be included right now, but I'm just curious if this may come up in the future.

Finally, I notice that you updated the Markdown file but not `standard_names.xml`; the easiest way to update names is to modify the xml and then use tools/write_standard_name_table.py to write the human-readable markdown file. But they do need to be consistent, otherwise the test will keep failing.

2024-12-13 01:42 UTC, jeromebarre commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = kg m-2 s-1
this makes very long names... can we keep to my original suggestion?

2024-12-13 01:49 UTC, jeromebarre commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = kg m-2 s-1
another suggestion: `no_emissions_from_anthropogenic_power` that keeps it concise. I think that `due_to` and `from` are the same meaning. 

Usually residential and commercial are lumped together in inventories. The acronym is usually RCO, residential. commercial and others. Can we possibly to to condense the long name with the acronym and be explicit in the description? Like 'no_emissions_from_anthropogenic_rco'?

2024-12-13 02:03 UTC, jeromebarre commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = kg m-2 s-1
I would try to avoid `emissions_of_anthropogenic` as there can be emission of fire and other processes. I would rather specify this in the suffix. The variable is <emission of something> the suffix is <from an emission sector>. The emission sector can be either a natural fire, a human emission or something else (natural emissions, wetlands, etc, etc). The granularity of such a sector can vary. Things are usually lumped so `total` should not be a prefix. It can be the total of anthropogenic, it can be the total of all emissions. So to remove this ambiguity, we can drop the total suffix/prefix here.

2024-12-13 15:44 UTC, mkavulich commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = kg m-2 s-1
@jeromebarre Thanks for your comments; I have updated my suggestions. I don't mind the inclusion of "RCO" if it is an accepted acronym/term in the field, we should just be sure it is added to the "Acronyms, Abbreviations, and Aliases" section of StandardNamesRules.rst. Especially I think if "other" is included in the variable then it should be included in the name and not just implied.

2024-12-19 16:49 UTC, cacraigucar commented
@mattldawson Could you run these by some of the ACOM scientists?

2024-12-19 17:16 UTC, jeromebarre commented
I will update this PR soon at add more species and sectors. Btw, the reference papers for those emissions are in:
https://essd.copernicus.org/articles/12/3413/2020/

2024-12-19 17:54 UTC, jeromebarre commented
> @mattldawson Could you run these by some of the ACOM scientists?

I was an ACOM scientist for a while. :)

2024-12-19 17:56 UTC, jeromebarre commented on Metadata-standard-names.md
> +    * `real(kind=kind_phys)`: units = kg m-2 s-1
I have updated the names according to your comments

2025-01-09 21:34 UTC, mkavulich commented
@jeromebarre We heard feedback from ACOM that they have no strong opinions, so one you update the XML to be consistent with the markdown file (and update your branch to include the latest changes) this PR should be ready. Let me know if you need any help with that process.

2025-01-09 22:35 UTC, gold2718 commented
> so one you update the XML to be consistent with the markdown file

This is something I wondered about. Don't we normally update the XML file and then run `tools/write_standard_name_table.py` as described in the `[README](https://github.com/ESCOMP/CCPPStandardNames/blob/main/README.md)?

2025-01-23 16:23 UTC, mkavulich commented
@gold2718 Yes, this is the standard practice, I am not sure which would be easier for @jeromebarre. I would suggest running the script after updating the xml regardless to make sure the unit test passes.

2025-01-27 16:21 UTC, jeromebarre commented
I can run that script, no problem. I'll try to finish this shortly. Thanks for the helpful reviews.

2025-01-31 18:10 UTC, jeromebarre commented
I have updated the xml and run the script as indicated. Let me know if there is anything else I need to do for this to be merged now. Thanks

2025-01-31 20:47 UTC, mkavulich requested changes
@jeromebarre Sorry I did not notice this on your last round of changes, but as I mentioned in my original review, I'd like the "other" component to be explicitly part of the filename if the variable includes those emissions; since it seems that "RCO" is a standard term in the field I suggest we use that

2025-01-31 20:47 UTC, mkavulich commented on Metadata-standard-names.md
> +* `emissions_of_co_due_to_anthropogenic_residential_commercial`: Carbon monoxide emissions from anthropogenic residential, commercial, and others
```suggestion
* `emissions_of_co_due_to_anthropogenic_rco`: Carbon monoxide emissions from anthropogenic residential, commercial, and others
```

2025-01-31 20:47 UTC, mkavulich commented on Metadata-standard-names.md
> +* `emissions_of_no_due_to_anthropogenic_residential_commercial`: Nitric oxide emissions from anthropogenic residential, commercial, and others
```suggestion
* `emissions_of_no_due_to_anthropogenic_rco`: Nitric oxide emissions from anthropogenic residential, commercial, and others
```

2025-01-31 20:47 UTC, mkavulich commented on Metadata-standard-names.md
> +* `emissions_of_hcho_due_to_anthropogenic_residential_commercial`: Formaldehyde emissions from anthropogenic residential, commercial, and others
```suggestion
* `emissions_of_hcho_due_to_anthropogenic_rco`: Formaldehyde emissions from anthropogenic residential, commercial, and others
```

2025-01-31 20:47 UTC, mkavulich commented on standard_names.xml
> +    <standard_name name="emissions_of_co_due_to_anthropogenic_residential_commercial"
```suggestion
    <standard_name name="emissions_of_co_due_to_anthropogenic_rco"
```

2025-01-31 20:47 UTC, mkavulich commented on standard_names.xml
> +    <standard_name name="emissions_of_no_due_to_anthropogenic_residential_commercial"
```suggestion
    <standard_name name="emissions_of_no_due_to_anthropogenic_rco"
```

2025-01-31 20:47 UTC, mkavulich commented on standard_names.xml
> +    <standard_name name="emissions_of_hcho_due_to_anthropogenic_residential_commercial"
```suggestion
    <standard_name name="emissions_of_hcho_due_to_anthropogenic_rco"
```

2025-02-04 14:56 UTC, jeromebarre commented
> @jeromebarre Sorry I did not notice this on your last round of changes, but as I mentioned in my original review, I'd like the "other" component to be explicitly part of the filename if the variable includes those emissions; since it seems that "RCO" is a standard term in the field I suggest we use that

I have now accepted and committed your suggested changes.

2025-02-05 09:23 UTC, gold2718 approved these changes
I have a small adjustment request but otherwise, this looks great.

2025-02-05 09:23 UTC, gold2718 commented on standard_names.xml
> +    </standard_name>
Just a grammatical nit but I think the long names of these would read better with a object for the adjective, 'anthropogenic'.
```suggestion
  <section name="emissions: Community Emissions Data System (CEDS)">
    <standard_name name="emissions_of_co_due_to_anthropogenic"
                   long_name="Carbon monoxide emissions from anthropogenic sources, total">
      <type kind="kind_phys" units="kg m-2 s-1">real</type>
    </standard_name>
    <standard_name name="emissions_of_no_due_to_anthropogenic"
                   long_name="Nitric oxide emissions from anthropogenic sources, total">
      <type kind="kind_phys" units="kg m-2 s-1">real</type>
    </standard_name>
    <standard_name name="emissions_of_hcho_due_to_anthropogenic"
                   long_name="Formaldehyde emissions from anthropogenic sources, total">
      <type kind="kind_phys" units="kg m-2 s-1">real</type>
    </standard_name>
```

2025-02-05 16:35 UTC, mkavulich commented
@jeromebarre Thanks for your patience through this process. You'll need to run the `tools/write_standard_name_table.py` tool one more time to update the markdown with the latest xml changes, but once that's done everything looks good for merging!

2025-02-13 15:34 UTC, mkavulich approved these changes
Jerome, I just realized I have push permissions to your fork, so I took the initiative to run the metadata update script. Now that all tests are passing I'll go ahead and merge.

2025-02-13 15:35 UTC, merged

2025-02-13 16:37 UTC, jeromebarre commented
@mkavulich thanks for that!